import type { Prisma } from '@prisma/client';

export const SERVICE_TOPOLOGY_SEED: Prisma.PlatformServiceTopologyCreateManyInput[] = [
  {
    key: 'service.api',
    kind: 'service',
    display_name: 'API service',
    description: 'NestJS API handling auth, tenant resolution, RBAC, and platform admin endpoints.',
    depends_on_keys: ['dependency.postgres', 'dependency.redis'],
    affects_product_areas: ['All authenticated workflows', 'Platform Admin'],
    suspected_repo_areas: ['apps/api/src'],
    related_components: ['postgresql', 'redis'],
  },
  {
    key: 'service.worker',
    kind: 'service',
    display_name: 'Worker service',
    description:
      'BullMQ processors for async jobs, cron dispatch, notifications, PDFs, and analytics.',
    depends_on_keys: ['dependency.postgres', 'dependency.redis'],
    affects_product_areas: ['Notifications', 'Reports', 'Finance', 'Scheduling', 'Imports'],
    suspected_repo_areas: ['apps/worker/src'],
    related_components: ['postgresql', 'redis', 'bullmq'],
  },
  {
    key: 'dependency.postgres',
    kind: 'dependency',
    display_name: 'PostgreSQL',
    description: 'Primary relational database with platform tables and tenant-scoped RLS tables.',
    affects_product_areas: ['All product areas'],
    suspected_repo_areas: ['packages/prisma', 'apps/api/src/modules/prisma'],
    related_components: ['postgresql'],
  },
  {
    key: 'dependency.redis',
    kind: 'dependency',
    display_name: 'Redis',
    description: 'Sessions, cache, rate limiting, and BullMQ coordination.',
    affects_product_areas: ['Login', 'Permissions', 'Queues', 'Notifications'],
    suspected_repo_areas: ['apps/api/src/modules/redis', 'apps/worker/src'],
    related_components: ['redis', 'bullmq'],
  },
  {
    key: 'queue.notifications',
    kind: 'queue',
    display_name: 'Notifications queue',
    description: 'Email, WhatsApp, SMS, in-app fanout, and retry processing.',
    depends_on_keys: ['service.worker', 'dependency.redis'],
    affects_product_areas: ['Communications', 'Parent Portal', 'Alerts'],
    suspected_repo_areas: [
      'apps/worker/src/processors/notifications',
      'apps/api/src/modules/communications',
    ],
    related_queue_names: ['notifications'],
    related_components: ['bullmq', 'redis'],
  },
  {
    key: 'queue.reports',
    kind: 'queue',
    display_name: 'Reports queue',
    description: 'Scheduled report delivery, exports, and maintenance-window checks.',
    depends_on_keys: ['service.worker', 'dependency.redis'],
    affects_product_areas: ['Reports', 'Compliance', 'Leadership dashboards'],
    suspected_repo_areas: ['apps/worker/src/processors/reports', 'apps/api/src/modules/reports'],
    related_queue_names: ['reports'],
    related_components: ['bullmq', 'redis'],
  },
  {
    key: 'module.finance',
    kind: 'module',
    display_name: 'Finance module',
    description: 'Fees, invoices, payments, refunds, payroll-facing finance operations.',
    depends_on_keys: ['service.api', 'dependency.postgres'],
    affects_product_areas: ['Billing', 'Parent Portal', 'Receipts'],
    suspected_repo_areas: [
      'apps/api/src/modules/finance',
      'apps/web/src/app/[locale]/(school)/finance',
    ],
    related_module_keys: ['finance', 'payments', 'invoices'],
    related_components: ['postgresql'],
  },
  {
    key: 'module.auth',
    kind: 'module',
    display_name: 'Authentication and sessions',
    description: 'Login, refresh tokens, platform access, tenant switching, and permission cache.',
    depends_on_keys: ['service.api', 'dependency.redis', 'dependency.postgres'],
    affects_product_areas: ['Login', 'Platform Admin', 'All authenticated workflows'],
    suspected_repo_areas: ['apps/api/src/modules/auth', 'apps/web/src/lib/api-client.ts'],
    related_components: ['redis', 'postgresql'],
  },
];

export const SEVERITY_POLICY_SEED: Prisma.PlatformSeverityPolicyCreateManyInput[] = [
  {
    key: 'auth.multi_tenant.failure',
    title: 'Multi-tenant auth failure',
    component: 'auth',
    product_area: 'Login',
    tenant_scope: 'multi_tenant',
    condition_config: { error_rate_5m_gte: 5, affected_tenants_gte: 2 },
    severity: 'critical',
    operator_guidance:
      'Treat as user-impacting. Check Redis, PostgreSQL, auth errors, and the latest deploy.',
  },
  {
    key: 'postgres.unhealthy',
    title: 'PostgreSQL unhealthy',
    component: 'postgresql',
    product_area: 'All product areas',
    tenant_scope: 'platform',
    condition_config: { health_status: 'unhealthy' },
    severity: 'critical',
    operator_guidance:
      'All tenant data access may be affected. Prioritise database health and rollback context.',
  },
  {
    key: 'redis.degraded.no_queue_growth',
    title: 'Redis degraded without queue growth',
    component: 'redis',
    product_area: 'Sessions and queues',
    tenant_scope: 'platform',
    condition_config: { health_status: 'degraded', queue_depth_growth: false },
    severity: 'warning',
    operator_guidance:
      'Monitor closely. User impact is likely limited unless sessions or queues degrade further.',
  },
  {
    key: 'bullmq.failed_jobs.growing',
    title: 'Failed jobs increasing',
    component: 'bullmq',
    product_area: 'Background processing',
    tenant_scope: 'any',
    condition_config: { failed_jobs_delta_gte: 10 },
    severity: 'warning',
    operator_guidance:
      'Inspect queue diagnostics and correlate with deploys, errors, and affected product areas.',
  },
  {
    key: 'single_tenant.onboarding.delay',
    title: 'Single-tenant onboarding delay',
    component: 'onboarding',
    product_area: 'Tenant onboarding',
    tenant_scope: 'single_tenant',
    condition_config: { blocked_hours_gte: 24 },
    severity: 'warning',
    operator_guidance:
      'Likely operational rather than platform-wide. Check onboarding steps and tenant audit trail.',
  },
];
