export const NOTIFICATION_TYPES = [
  'invoice.issued',
  'payment.received',
  'payment.failed',
  'report_card.published',
  'attendance.exception',
  'attendance.absent',
  'attendance.late',
  'attendance.left_early',
  'attendance.pattern_detected',
  'admission.status_change',
  'announcement.published',
  'approval.requested',
  'approval.decided',
  'inquiry.new_message',
  'payroll.finalised',
  'payslip.generated',
  'parent.daily_digest',
  // ─── Added by Impl 12 (Communications Overhaul gap closure) ────────────────
  'auth.password_reset',
  'auth.password_changed',
  'trip.invitation',
  'trip.payment_due',
  'school.closure',
  'staff.leave_decision',
  'health.incident',
  'sen.eha_update',
] as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[number];
