import type { RoleTier } from '../types/rbac';

export const PERMISSIONS = {
  // Platform tier
  tenants: {
    manage: 'tenants.manage',
    view: 'tenants.view',
  },
  platform: {
    impersonate: 'platform.impersonate',
    reset_mfa: 'platform.reset_mfa',
  },
  // Admin tier
  users: {
    manage: 'users.manage',
    invite: 'users.invite',
    view: 'users.view',
  },
  roles: {
    manage: 'roles.manage',
  },
  settings: {
    manage: 'settings.manage',
  },
  branding: {
    manage: 'branding.manage',
  },
  stripe: {
    manage: 'stripe.manage',
  },
  notifications: {
    manage: 'notifications.manage',
  },
  modules: {
    manage: 'modules.manage',
  },
  domains: {
    manage: 'domains.manage',
  },
  approvals: {
    manage: 'approvals.manage',
    view: 'approvals.view',
  },
  // Payroll (admin tier)
  payroll: {
    view: 'payroll.view',
    manage_compensation: 'payroll.manage_compensation',
    create_run: 'payroll.create_run',
    finalise_run: 'payroll.finalise_run',
    generate_payslips: 'payroll.generate_payslips',
    view_bank_details: 'payroll.view_bank_details',
    view_reports: 'payroll.view_reports',
    manage_attendance: 'payroll.manage_attendance',
    manage_class_delivery: 'payroll.manage_class_delivery',
    manage_exports: 'payroll.manage_exports',
    manage_allowances: 'payroll.manage_allowances',
    manage_deductions: 'payroll.manage_deductions',
  },
  // Schedule (admin tier)
  schedule_admin: {
    manage: 'schedule.manage',
    override_conflict: 'schedule.override_conflict',
    manage_closures: 'schedule.manage_closures',
    configure_period_grid: 'schedule.configure_period_grid',
    configure_requirements: 'schedule.configure_requirements',
    configure_availability: 'schedule.configure_availability',
    manage_preferences: 'schedule.manage_preferences',
    run_auto: 'schedule.run_auto',
    apply_auto: 'schedule.apply_auto',
    pin_entries: 'schedule.pin_entries',
    view_auto_reports: 'schedule.view_auto_reports',
  },
  // Schedule enhanced (admin tier)
  schedule_enhanced: {
    manage_substitutions: 'schedule.manage_substitutions',
    view_reports: 'schedule.view_reports',
    manage_exams: 'schedule.manage_exams',
    manage_scenarios: 'schedule.manage_scenarios',
  },
  // Schedule (staff tier)
  schedule_staff: {
    view_own: 'schedule.view_own',
    manage_own_preferences: 'schedule.manage_own_preferences',
    view_own_satisfaction: 'schedule.view_own_satisfaction',
    view_personal_timetable: 'schedule.view_personal_timetable',
  },
  // Students (admin tier)
  students: {
    manage: 'students.manage',
    view: 'students.view',
  },
  // Attendance (admin/staff tier)
  attendance: {
    manage: 'attendance.manage',
    view: 'attendance.view',
    take: 'attendance.take',
    amend_historical: 'attendance.amend_historical',
    override_closure: 'attendance.override_closure',
    view_pattern_reports: 'attendance.view_pattern_reports',
  },
  // Gradebook
  gradebook: {
    manage: 'gradebook.manage',
    view: 'gradebook.view',
    enter_grades: 'gradebook.enter_grades',
    override_final_grade: 'gradebook.override_final_grade',
    publish_report_cards: 'gradebook.publish_report_cards',
    apply_curve: 'gradebook.apply_curve',
    view_analytics: 'gradebook.view_analytics',
    publish_grades_to_parents: 'gradebook.publish_grades_to_parents',
    manage_ai_grading: 'gradebook.manage_ai_grading',
    approve_ai_grading: 'gradebook.approve_ai_grading',
    manage_own_config: 'gradebook.manage_own_config',
    approve_config: 'gradebook.approve_config',
    request_unlock: 'gradebook.request_unlock',
    approve_unlock: 'gradebook.approve_unlock',
  },
  // Report Cards (enhanced)
  report_cards: {
    approve: 'report_cards.approve',
    manage_templates: 'report_cards.manage_templates',
    bulk_operations: 'report_cards.bulk_operations',
  },
  // Transcripts
  transcripts: {
    generate: 'transcripts.generate',
  },
  // Admissions (admin)
  admissions: {
    manage: 'admissions.manage',
    view: 'admissions.view',
  },
  // Finance (admin)
  finance: {
    manage: 'finance.manage',
    view: 'finance.view',
    process_payments: 'finance.process_payments',
    issue_refunds: 'finance.issue_refunds',
    write_off: 'finance.write_off',
    override_refund_guard: 'finance.override_refund_guard',
    manage_credit_notes: 'finance.manage_credit_notes',
    manage_scholarships: 'finance.manage_scholarships',
    manage_late_fees: 'finance.manage_late_fees',
    view_reports: 'finance.view_reports',
    bulk_operations: 'finance.bulk_operations',
  },
  // Communications (admin)
  communications: {
    manage: 'communications.manage',
    view: 'communications.view',
    send: 'communications.send',
  },
  // Inquiries (admin tier)
  inquiries: {
    view: 'inquiries.view',
    respond: 'inquiries.respond',
  },
  // Website (admin)
  website: {
    manage: 'website.manage',
  },
  // Analytics (admin)
  analytics: {
    view: 'analytics.view',
    manage_reports: 'analytics.manage_reports',
    view_board_reports: 'analytics.view_board_reports',
    manage_compliance: 'analytics.manage_compliance',
  },
  // Curriculum Matrix (admin)
  curriculum_matrix: {
    manage: 'curriculum_matrix.manage',
  },
  // Compliance (admin)
  compliance: {
    manage: 'compliance.manage',
    view: 'compliance.view',
  },
  // GDPR (admin)
  gdpr: {
    view: 'gdpr.view',
  },
  legal: {
    view: 'legal.view',
    manage: 'legal.manage',
  },
  privacy: {
    view: 'privacy.view',
    manage: 'privacy.manage',
  },
  consent: {
    manage: 'consent.manage',
    view: 'consent.view',
  },
  // Behaviour (admin + staff tier)
  behaviour: {
    log: 'behaviour.log',
    view: 'behaviour.view',
    manage: 'behaviour.manage',
    admin: 'behaviour.admin',
    view_sensitive: 'behaviour.view_sensitive',
    view_staff_analytics: 'behaviour.view_staff_analytics',
    ai_query: 'behaviour.ai_query',
    appeal: 'behaviour.appeal',
  },
  // SEN (admin + staff tier)
  sen: {
    view: 'sen.view',
    manage: 'sen.manage',
    manage_resources: 'sen.manage_resources',
    view_sensitive: 'sen.view_sensitive',
    admin: 'sen.admin',
  },
  // Safeguarding (admin tier)
  safeguarding: {
    report: 'safeguarding.report',
    view: 'safeguarding.view',
    manage: 'safeguarding.manage',
    seal: 'safeguarding.seal',
  },
  // Inbox / messaging (mixed tiers — see PERMISSION_TIER_MAP below)
  inbox: {
    settings_read: 'inbox.settings.read',
    settings_write: 'inbox.settings.write',
    send: 'inbox.send',
    oversight_read: 'inbox.oversight.read',
    oversight_write: 'inbox.oversight.write',
  },
  // Parent tier
  parent_portal: {
    view_own_students: 'parent.view_own_students',
    view_attendance: 'parent.view_attendance',
    view_grades: 'parent.view_grades',
    view_invoices: 'parent.view_invoices',
    view_finances: 'parent.view_finances',
    make_payments: 'parent.make_payments',
    submit_inquiry: 'parent.submit_inquiry',
    view_announcements: 'parent.view_announcements',
    view_transcripts: 'parent.view_transcripts',
    view_timetable: 'parent.view_timetable',
  },
} as const;

/** Map every permission key to its role tier */
export const PERMISSION_TIER_MAP: Record<string, RoleTier> = {
  // Platform tier
  [PERMISSIONS.tenants.manage]: 'platform',
  [PERMISSIONS.tenants.view]: 'platform',
  [PERMISSIONS.platform.impersonate]: 'platform',
  [PERMISSIONS.platform.reset_mfa]: 'platform',

  // Admin tier
  [PERMISSIONS.users.manage]: 'admin',
  [PERMISSIONS.users.invite]: 'admin',
  [PERMISSIONS.users.view]: 'admin',
  [PERMISSIONS.roles.manage]: 'admin',
  [PERMISSIONS.settings.manage]: 'admin',
  [PERMISSIONS.branding.manage]: 'admin',
  [PERMISSIONS.stripe.manage]: 'admin',
  [PERMISSIONS.notifications.manage]: 'admin',
  [PERMISSIONS.modules.manage]: 'admin',
  [PERMISSIONS.domains.manage]: 'admin',
  [PERMISSIONS.approvals.manage]: 'admin',
  [PERMISSIONS.approvals.view]: 'admin',
  [PERMISSIONS.payroll.view]: 'admin',
  [PERMISSIONS.payroll.manage_compensation]: 'admin',
  [PERMISSIONS.payroll.create_run]: 'admin',
  [PERMISSIONS.payroll.finalise_run]: 'admin',
  [PERMISSIONS.payroll.generate_payslips]: 'admin',
  [PERMISSIONS.payroll.view_bank_details]: 'admin',
  [PERMISSIONS.payroll.view_reports]: 'admin',
  [PERMISSIONS.payroll.manage_attendance]: 'admin',
  [PERMISSIONS.payroll.manage_class_delivery]: 'admin',
  [PERMISSIONS.payroll.manage_exports]: 'admin',
  [PERMISSIONS.payroll.manage_allowances]: 'admin',
  [PERMISSIONS.payroll.manage_deductions]: 'admin',
  [PERMISSIONS.schedule_admin.manage]: 'admin',
  [PERMISSIONS.schedule_admin.override_conflict]: 'admin',
  [PERMISSIONS.schedule_admin.manage_closures]: 'admin',
  [PERMISSIONS.schedule_admin.configure_period_grid]: 'admin',
  [PERMISSIONS.schedule_admin.configure_requirements]: 'admin',
  [PERMISSIONS.schedule_admin.configure_availability]: 'admin',
  [PERMISSIONS.schedule_admin.manage_preferences]: 'admin',
  [PERMISSIONS.schedule_admin.run_auto]: 'admin',
  [PERMISSIONS.schedule_admin.apply_auto]: 'admin',
  [PERMISSIONS.schedule_admin.pin_entries]: 'admin',
  [PERMISSIONS.schedule_admin.view_auto_reports]: 'admin',
  [PERMISSIONS.schedule_enhanced.manage_substitutions]: 'admin',
  [PERMISSIONS.schedule_enhanced.view_reports]: 'admin',
  [PERMISSIONS.schedule_enhanced.manage_exams]: 'admin',
  [PERMISSIONS.schedule_enhanced.manage_scenarios]: 'admin',
  [PERMISSIONS.students.manage]: 'admin',
  [PERMISSIONS.students.view]: 'admin',
  [PERMISSIONS.attendance.manage]: 'admin',
  [PERMISSIONS.attendance.view]: 'admin',
  [PERMISSIONS.attendance.amend_historical]: 'admin',
  [PERMISSIONS.attendance.override_closure]: 'admin',
  [PERMISSIONS.attendance.view_pattern_reports]: 'admin',
  [PERMISSIONS.gradebook.manage]: 'admin',
  [PERMISSIONS.gradebook.view]: 'admin',
  [PERMISSIONS.gradebook.override_final_grade]: 'admin',
  [PERMISSIONS.gradebook.publish_report_cards]: 'admin',
  [PERMISSIONS.gradebook.apply_curve]: 'admin',
  [PERMISSIONS.gradebook.view_analytics]: 'admin',
  [PERMISSIONS.gradebook.publish_grades_to_parents]: 'admin',
  [PERMISSIONS.gradebook.approve_ai_grading]: 'admin',
  [PERMISSIONS.gradebook.approve_config]: 'admin',
  [PERMISSIONS.gradebook.approve_unlock]: 'admin',
  [PERMISSIONS.report_cards.approve]: 'admin',
  [PERMISSIONS.report_cards.manage_templates]: 'admin',
  [PERMISSIONS.report_cards.bulk_operations]: 'admin',
  [PERMISSIONS.transcripts.generate]: 'admin',
  [PERMISSIONS.admissions.manage]: 'admin',
  [PERMISSIONS.admissions.view]: 'admin',
  [PERMISSIONS.finance.manage]: 'admin',
  [PERMISSIONS.finance.view]: 'admin',
  [PERMISSIONS.finance.process_payments]: 'admin',
  [PERMISSIONS.finance.issue_refunds]: 'admin',
  [PERMISSIONS.finance.write_off]: 'admin',
  [PERMISSIONS.finance.override_refund_guard]: 'admin',
  [PERMISSIONS.finance.manage_credit_notes]: 'admin',
  [PERMISSIONS.finance.manage_scholarships]: 'admin',
  [PERMISSIONS.finance.manage_late_fees]: 'admin',
  [PERMISSIONS.finance.view_reports]: 'admin',
  [PERMISSIONS.finance.bulk_operations]: 'admin',
  [PERMISSIONS.communications.manage]: 'admin',
  [PERMISSIONS.communications.view]: 'admin',
  [PERMISSIONS.communications.send]: 'admin',
  [PERMISSIONS.inquiries.view]: 'admin',
  [PERMISSIONS.inquiries.respond]: 'admin',
  [PERMISSIONS.website.manage]: 'admin',
  [PERMISSIONS.analytics.view]: 'admin',
  [PERMISSIONS.analytics.manage_reports]: 'admin',
  [PERMISSIONS.analytics.view_board_reports]: 'admin',
  [PERMISSIONS.analytics.manage_compliance]: 'admin',
  [PERMISSIONS.curriculum_matrix.manage]: 'admin',
  [PERMISSIONS.compliance.manage]: 'admin',
  [PERMISSIONS.compliance.view]: 'admin',
  [PERMISSIONS.gdpr.view]: 'admin',
  [PERMISSIONS.legal.view]: 'parent',
  [PERMISSIONS.legal.manage]: 'admin',
  [PERMISSIONS.privacy.view]: 'admin',
  [PERMISSIONS.privacy.manage]: 'admin',
  [PERMISSIONS.consent.manage]: 'admin',
  [PERMISSIONS.consent.view]: 'admin',
  [PERMISSIONS.behaviour.admin]: 'admin',
  [PERMISSIONS.behaviour.view_staff_analytics]: 'admin',
  [PERMISSIONS.sen.manage_resources]: 'admin',
  [PERMISSIONS.sen.admin]: 'admin',
  [PERMISSIONS.safeguarding.view]: 'admin',
  [PERMISSIONS.safeguarding.manage]: 'admin',
  [PERMISSIONS.safeguarding.seal]: 'admin',

  // Staff tier
  [PERMISSIONS.schedule_staff.view_own]: 'staff',
  [PERMISSIONS.schedule_staff.manage_own_preferences]: 'staff',
  [PERMISSIONS.schedule_staff.view_own_satisfaction]: 'staff',
  [PERMISSIONS.schedule_staff.view_personal_timetable]: 'staff',
  [PERMISSIONS.attendance.take]: 'staff',
  [PERMISSIONS.gradebook.enter_grades]: 'staff',
  [PERMISSIONS.gradebook.manage_ai_grading]: 'staff',
  [PERMISSIONS.gradebook.manage_own_config]: 'staff',
  [PERMISSIONS.gradebook.request_unlock]: 'staff',
  [PERMISSIONS.behaviour.log]: 'staff',
  [PERMISSIONS.behaviour.view]: 'staff',
  [PERMISSIONS.behaviour.manage]: 'staff',
  [PERMISSIONS.behaviour.view_sensitive]: 'staff',
  [PERMISSIONS.behaviour.ai_query]: 'staff',
  [PERMISSIONS.sen.view]: 'staff',
  [PERMISSIONS.sen.manage]: 'staff',
  [PERMISSIONS.sen.view_sensitive]: 'staff',
  [PERMISSIONS.safeguarding.report]: 'staff',

  // Inbox / messaging
  [PERMISSIONS.inbox.settings_read]: 'admin',
  [PERMISSIONS.inbox.settings_write]: 'admin',
  [PERMISSIONS.inbox.oversight_read]: 'admin',
  [PERMISSIONS.inbox.oversight_write]: 'admin',
  [PERMISSIONS.inbox.send]: 'staff',

  // Parent tier
  [PERMISSIONS.parent_portal.view_own_students]: 'parent',
  [PERMISSIONS.parent_portal.view_attendance]: 'parent',
  [PERMISSIONS.parent_portal.view_grades]: 'parent',
  [PERMISSIONS.parent_portal.view_invoices]: 'parent',
  [PERMISSIONS.parent_portal.view_finances]: 'parent',
  [PERMISSIONS.parent_portal.make_payments]: 'parent',
  [PERMISSIONS.parent_portal.submit_inquiry]: 'parent',
  [PERMISSIONS.parent_portal.view_announcements]: 'parent',
  [PERMISSIONS.parent_portal.view_transcripts]: 'parent',
  [PERMISSIONS.parent_portal.view_timetable]: 'parent',
  [PERMISSIONS.behaviour.appeal]: 'parent',
};

/** Default permission assignments for each system role */
export const SYSTEM_ROLE_PERMISSIONS: Record<string, string[]> = {
  platform_owner: [
    PERMISSIONS.tenants.manage,
    PERMISSIONS.tenants.view,
    PERMISSIONS.platform.impersonate,
    PERMISSIONS.platform.reset_mfa,
  ],

  school_owner: [
    // All admin-tier permissions
    PERMISSIONS.users.manage,
    PERMISSIONS.users.invite,
    PERMISSIONS.users.view,
    PERMISSIONS.roles.manage,
    PERMISSIONS.settings.manage,
    PERMISSIONS.branding.manage,
    PERMISSIONS.stripe.manage,
    PERMISSIONS.notifications.manage,
    PERMISSIONS.modules.manage,
    PERMISSIONS.domains.manage,
    PERMISSIONS.approvals.manage,
    PERMISSIONS.approvals.view,
    PERMISSIONS.payroll.view,
    PERMISSIONS.payroll.manage_compensation,
    PERMISSIONS.payroll.create_run,
    PERMISSIONS.payroll.finalise_run,
    PERMISSIONS.payroll.generate_payslips,
    PERMISSIONS.payroll.view_bank_details,
    PERMISSIONS.payroll.view_reports,
    PERMISSIONS.payroll.manage_attendance,
    PERMISSIONS.payroll.manage_class_delivery,
    PERMISSIONS.payroll.manage_exports,
    PERMISSIONS.payroll.manage_allowances,
    PERMISSIONS.payroll.manage_deductions,
    PERMISSIONS.schedule_admin.manage,
    PERMISSIONS.schedule_admin.override_conflict,
    PERMISSIONS.schedule_admin.manage_closures,
    PERMISSIONS.schedule_admin.configure_period_grid,
    PERMISSIONS.schedule_admin.configure_requirements,
    PERMISSIONS.schedule_admin.configure_availability,
    PERMISSIONS.schedule_admin.manage_preferences,
    PERMISSIONS.schedule_admin.run_auto,
    PERMISSIONS.schedule_admin.apply_auto,
    PERMISSIONS.schedule_admin.pin_entries,
    PERMISSIONS.schedule_admin.view_auto_reports,
    PERMISSIONS.schedule_enhanced.manage_substitutions,
    PERMISSIONS.schedule_enhanced.view_reports,
    PERMISSIONS.schedule_enhanced.manage_exams,
    PERMISSIONS.schedule_enhanced.manage_scenarios,
    PERMISSIONS.students.manage,
    PERMISSIONS.students.view,
    PERMISSIONS.attendance.manage,
    PERMISSIONS.attendance.view,
    PERMISSIONS.attendance.amend_historical,
    PERMISSIONS.attendance.override_closure,
    PERMISSIONS.attendance.view_pattern_reports,
    PERMISSIONS.gradebook.manage,
    PERMISSIONS.gradebook.view,
    PERMISSIONS.gradebook.override_final_grade,
    PERMISSIONS.gradebook.publish_report_cards,
    PERMISSIONS.gradebook.apply_curve,
    PERMISSIONS.gradebook.view_analytics,
    PERMISSIONS.gradebook.publish_grades_to_parents,
    PERMISSIONS.gradebook.manage_ai_grading,
    PERMISSIONS.gradebook.approve_ai_grading,
    PERMISSIONS.gradebook.manage_own_config,
    PERMISSIONS.gradebook.approve_config,
    PERMISSIONS.gradebook.request_unlock,
    PERMISSIONS.gradebook.approve_unlock,
    PERMISSIONS.report_cards.approve,
    PERMISSIONS.report_cards.manage_templates,
    PERMISSIONS.report_cards.bulk_operations,
    PERMISSIONS.transcripts.generate,
    PERMISSIONS.admissions.manage,
    PERMISSIONS.admissions.view,
    PERMISSIONS.finance.manage,
    PERMISSIONS.finance.view,
    PERMISSIONS.finance.process_payments,
    PERMISSIONS.finance.issue_refunds,
    PERMISSIONS.finance.write_off,
    PERMISSIONS.finance.override_refund_guard,
    PERMISSIONS.finance.manage_credit_notes,
    PERMISSIONS.finance.manage_scholarships,
    PERMISSIONS.finance.manage_late_fees,
    PERMISSIONS.finance.view_reports,
    PERMISSIONS.finance.bulk_operations,
    PERMISSIONS.communications.manage,
    PERMISSIONS.communications.view,
    PERMISSIONS.communications.send,
    PERMISSIONS.inquiries.view,
    PERMISSIONS.inquiries.respond,
    PERMISSIONS.website.manage,
    PERMISSIONS.analytics.view,
    PERMISSIONS.analytics.manage_reports,
    PERMISSIONS.analytics.view_board_reports,
    PERMISSIONS.analytics.manage_compliance,
    PERMISSIONS.curriculum_matrix.manage,
    PERMISSIONS.compliance.manage,
    PERMISSIONS.compliance.view,
    PERMISSIONS.gdpr.view,
    PERMISSIONS.legal.view,
    PERMISSIONS.legal.manage,
    PERMISSIONS.privacy.view,
    PERMISSIONS.privacy.manage,
    PERMISSIONS.consent.manage,
    PERMISSIONS.consent.view,
    // Behaviour + safeguarding (all)
    PERMISSIONS.behaviour.log,
    PERMISSIONS.behaviour.view,
    PERMISSIONS.behaviour.manage,
    PERMISSIONS.behaviour.admin,
    PERMISSIONS.behaviour.view_sensitive,
    PERMISSIONS.behaviour.view_staff_analytics,
    PERMISSIONS.behaviour.ai_query,
    PERMISSIONS.sen.view,
    PERMISSIONS.sen.manage,
    PERMISSIONS.sen.manage_resources,
    PERMISSIONS.sen.view_sensitive,
    PERMISSIONS.sen.admin,
    PERMISSIONS.safeguarding.report,
    PERMISSIONS.safeguarding.view,
    PERMISSIONS.safeguarding.manage,
    PERMISSIONS.safeguarding.seal,
    // Inbox — admin tier (all five keys)
    PERMISSIONS.inbox.settings_read,
    PERMISSIONS.inbox.settings_write,
    PERMISSIONS.inbox.send,
    PERMISSIONS.inbox.oversight_read,
    PERMISSIONS.inbox.oversight_write,
  ],

  school_admin: [
    PERMISSIONS.users.manage,
    PERMISSIONS.users.invite,
    PERMISSIONS.users.view,
    PERMISSIONS.roles.manage,
    PERMISSIONS.settings.manage,
    PERMISSIONS.branding.manage,
    PERMISSIONS.notifications.manage,
    PERMISSIONS.modules.manage,
    PERMISSIONS.domains.manage,
    PERMISSIONS.approvals.manage,
    PERMISSIONS.approvals.view,
    PERMISSIONS.schedule_admin.manage,
    PERMISSIONS.schedule_admin.override_conflict,
    PERMISSIONS.schedule_admin.manage_closures,
    PERMISSIONS.schedule_admin.configure_period_grid,
    PERMISSIONS.schedule_admin.configure_requirements,
    PERMISSIONS.schedule_admin.configure_availability,
    PERMISSIONS.schedule_admin.manage_preferences,
    PERMISSIONS.schedule_admin.run_auto,
    PERMISSIONS.schedule_admin.apply_auto,
    PERMISSIONS.schedule_admin.pin_entries,
    PERMISSIONS.schedule_admin.view_auto_reports,
    PERMISSIONS.schedule_enhanced.manage_substitutions,
    PERMISSIONS.schedule_enhanced.view_reports,
    PERMISSIONS.schedule_enhanced.manage_exams,
    PERMISSIONS.schedule_enhanced.manage_scenarios,
    PERMISSIONS.students.manage,
    PERMISSIONS.students.view,
    PERMISSIONS.attendance.manage,
    PERMISSIONS.attendance.view,
    PERMISSIONS.attendance.amend_historical,
    PERMISSIONS.attendance.override_closure,
    PERMISSIONS.attendance.view_pattern_reports,
    PERMISSIONS.gradebook.manage,
    PERMISSIONS.gradebook.view,
    PERMISSIONS.gradebook.override_final_grade,
    PERMISSIONS.gradebook.publish_report_cards,
    PERMISSIONS.gradebook.apply_curve,
    PERMISSIONS.gradebook.view_analytics,
    PERMISSIONS.gradebook.publish_grades_to_parents,
    PERMISSIONS.gradebook.manage_ai_grading,
    PERMISSIONS.gradebook.approve_ai_grading,
    PERMISSIONS.gradebook.manage_own_config,
    PERMISSIONS.gradebook.approve_config,
    PERMISSIONS.gradebook.request_unlock,
    PERMISSIONS.gradebook.approve_unlock,
    PERMISSIONS.report_cards.approve,
    PERMISSIONS.report_cards.manage_templates,
    PERMISSIONS.report_cards.bulk_operations,
    PERMISSIONS.transcripts.generate,
    PERMISSIONS.admissions.manage,
    PERMISSIONS.admissions.view,
    PERMISSIONS.communications.manage,
    PERMISSIONS.communications.view,
    PERMISSIONS.communications.send,
    PERMISSIONS.inquiries.view,
    PERMISSIONS.inquiries.respond,
    PERMISSIONS.website.manage,
    PERMISSIONS.analytics.view,
    PERMISSIONS.analytics.manage_reports,
    PERMISSIONS.analytics.view_board_reports,
    PERMISSIONS.analytics.manage_compliance,
    PERMISSIONS.compliance.manage,
    PERMISSIONS.compliance.view,
    PERMISSIONS.gdpr.view,
    PERMISSIONS.legal.view,
    PERMISSIONS.legal.manage,
    PERMISSIONS.privacy.view,
    PERMISSIONS.privacy.manage,
    PERMISSIONS.consent.manage,
    PERMISSIONS.consent.view,
    // Behaviour + safeguarding
    PERMISSIONS.behaviour.log,
    PERMISSIONS.behaviour.view,
    PERMISSIONS.behaviour.manage,
    PERMISSIONS.behaviour.admin,
    PERMISSIONS.behaviour.view_sensitive,
    PERMISSIONS.behaviour.view_staff_analytics,
    PERMISSIONS.behaviour.ai_query,
    PERMISSIONS.sen.view,
    PERMISSIONS.sen.manage,
    PERMISSIONS.sen.manage_resources,
    PERMISSIONS.sen.view_sensitive,
    PERMISSIONS.sen.admin,
    PERMISSIONS.safeguarding.report,
    PERMISSIONS.safeguarding.view,
    PERMISSIONS.safeguarding.manage,
    // Inbox — school_admin gets send + settings read/write, no oversight
    PERMISSIONS.inbox.settings_read,
    PERMISSIONS.inbox.settings_write,
    PERMISSIONS.inbox.send,
  ],

  teacher: [
    PERMISSIONS.schedule_staff.view_own,
    PERMISSIONS.schedule_staff.manage_own_preferences,
    PERMISSIONS.schedule_staff.view_own_satisfaction,
    PERMISSIONS.schedule_staff.view_personal_timetable,
    PERMISSIONS.attendance.take,
    PERMISSIONS.attendance.view,
    PERMISSIONS.gradebook.enter_grades,
    PERMISSIONS.gradebook.view,
    PERMISSIONS.gradebook.manage_ai_grading,
    PERMISSIONS.gradebook.manage_own_config,
    PERMISSIONS.gradebook.request_unlock,
    PERMISSIONS.students.view,
    PERMISSIONS.legal.view,
    PERMISSIONS.sen.view,
    // Behaviour (staff tier)
    PERMISSIONS.behaviour.log,
    PERMISSIONS.behaviour.view,
    PERMISSIONS.safeguarding.report,
    // Inbox — teachers can send
    PERMISSIONS.inbox.send,
  ],

  finance_staff: [
    PERMISSIONS.finance.manage,
    PERMISSIONS.finance.view,
    PERMISSIONS.finance.process_payments,
    PERMISSIONS.finance.write_off,
    PERMISSIONS.finance.manage_credit_notes,
    PERMISSIONS.finance.manage_scholarships,
    PERMISSIONS.finance.manage_late_fees,
    PERMISSIONS.finance.view_reports,
    PERMISSIONS.finance.bulk_operations,
    PERMISSIONS.legal.view,
    // Inbox — finance staff can send
    PERMISSIONS.inbox.send,
  ],

  admissions_staff: [
    PERMISSIONS.admissions.manage,
    PERMISSIONS.admissions.view,
    PERMISSIONS.legal.view,
    // Inbox — front-office / admissions staff can send
    PERMISSIONS.inbox.send,
  ],

  parent: [
    PERMISSIONS.parent_portal.view_own_students,
    PERMISSIONS.parent_portal.view_attendance,
    PERMISSIONS.parent_portal.view_grades,
    PERMISSIONS.parent_portal.view_invoices,
    PERMISSIONS.parent_portal.view_finances,
    PERMISSIONS.parent_portal.make_payments,
    PERMISSIONS.parent_portal.submit_inquiry,
    PERMISSIONS.parent_portal.view_announcements,
    PERMISSIONS.parent_portal.view_transcripts,
    PERMISSIONS.parent_portal.view_timetable,
    PERMISSIONS.legal.view,
    // Behaviour (parent tier)
    PERMISSIONS.behaviour.appeal,
    // Inbox — parents hold inbox.send so the policy engine (not the guard)
    // decides whether they may actually initiate or reply on a given thread.
    PERMISSIONS.inbox.send,
  ],
};
