import { NotFoundException } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';

import { PrismaService } from '../prisma/prisma.service';
import { SequenceService } from '../sequence/sequence.service';

import { BehaviourDocumentService } from './behaviour-document.service';
import { BehaviourHistoryService } from './behaviour-history.service';
import { BehaviourSanctionsCrudService } from './behaviour-sanctions-crud.service';
import { BehaviourSideEffectsService } from './behaviour-side-effects.service';

// ─── Constants ────────────────────────────────────────────────────────────────

const TENANT_ID = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
const USER_ID = 'user-1';
const INCIDENT_ID = 'incident-1';
const STUDENT_ID = 'student-1';
const SANCTION_ID = 'sanction-1';

// ─── RLS mock ─────────────────────────────────────────────────────────────────

const mockRlsTx = {
  behaviourSanction: {
    findFirst: jest.fn(),
    findUnique: jest.fn(),
    findMany: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    count: jest.fn(),
  },
  behaviourIncident: {
    findFirst: jest.fn(),
  },
  behaviourAmendmentNotice: {
    create: jest.fn(),
  },
  student: {
    findFirst: jest.fn(),
  },
  tenantSetting: {
    findFirst: jest.fn(),
  },
  schoolClosure: {
    findFirst: jest.fn(),
  },
  behaviourEntityHistory: {
    create: jest.fn(),
  },
};

jest.mock('../../common/middleware/rls.middleware', () => ({
  createRlsClient: jest.fn().mockReturnValue({
    $transaction: jest
      .fn()
      .mockImplementation(async (fn: (tx: unknown) => Promise<unknown>) => fn(mockRlsTx)),
  }),
}));

// ─── Factories ────────────────────────────────────────────────────────────────

const makeSanction = (overrides: Record<string, unknown> = {}) => ({
  id: SANCTION_ID,
  tenant_id: TENANT_ID,
  sanction_number: 'SN-202603-000001',
  incident_id: INCIDENT_ID,
  student_id: STUDENT_ID,
  type: 'detention',
  status: 'scheduled',
  scheduled_date: new Date('2026-03-20'),
  scheduled_start_time: null,
  scheduled_end_time: null,
  scheduled_room_id: null,
  supervised_by_id: null,
  suspension_start_date: null,
  suspension_end_date: null,
  suspension_days: null,
  return_conditions: null,
  parent_meeting_required: false,
  notes: null,
  served_at: null,
  retention_status: 'active',
  ...overrides,
});

const makeSettings = (overrides: Record<string, unknown> = {}) => ({
  settings: {
    behaviour: {
      suspension_requires_approval: false,
      expulsion_requires_approval: false,
      document_auto_generate_detention_notice: false,
      document_auto_generate_suspension_letter: true,
      ...overrides,
    },
  },
});

// ─── Test suite ───────────────────────────────────────────────────────────────

describe('BehaviourSanctionsCrudService', () => {
  let service: BehaviourSanctionsCrudService;
  let mockPrisma: {
    behaviourSanction: { findMany: jest.Mock; findFirst: jest.Mock; count: jest.Mock };
  };
  let mockSequence: { nextNumber: jest.Mock };
  let mockHistory: { recordHistory: jest.Mock };
  let mockSideEffects: {
    emitSanctionParentNotification: jest.Mock;
    emitCreateExclusionCase: jest.Mock;
  };
  let mockDocumentService: { autoGenerateDocument: jest.Mock };

  beforeEach(async () => {
    mockPrisma = {
      behaviourSanction: {
        findMany: jest.fn().mockResolvedValue([]),
        findFirst: jest.fn(),
        count: jest.fn().mockResolvedValue(0),
      },
    };
    mockSequence = {
      nextNumber: jest.fn().mockResolvedValue('SN-202603-000001'),
    };
    mockHistory = { recordHistory: jest.fn().mockResolvedValue(undefined) };
    mockSideEffects = {
      emitSanctionParentNotification: jest.fn().mockResolvedValue(undefined),
      emitCreateExclusionCase: jest.fn().mockResolvedValue(undefined),
    };
    mockDocumentService = {
      autoGenerateDocument: jest.fn().mockResolvedValue({ id: 'doc-1' }),
    };

    // Reset all RLS tx mocks
    for (const model of Object.values(mockRlsTx)) {
      for (const fn of Object.values(model)) {
        fn.mockReset();
      }
    }

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        BehaviourSanctionsCrudService,
        { provide: PrismaService, useValue: mockPrisma },
        { provide: SequenceService, useValue: mockSequence },
        { provide: BehaviourHistoryService, useValue: mockHistory },
        { provide: BehaviourDocumentService, useValue: mockDocumentService },
        { provide: BehaviourSideEffectsService, useValue: mockSideEffects },
      ],
    }).compile();

    service = module.get<BehaviourSanctionsCrudService>(BehaviourSanctionsCrudService);
  });

  afterEach(() => jest.clearAllMocks());

  // ─── create ────────────────────────────────────────────────────────────────

  describe('BehaviourSanctionsCrudService — create', () => {
    const baseDto = {
      incident_id: INCIDENT_ID,
      student_id: STUDENT_ID,
      type: 'detention' as const,
      scheduled_date: '2026-03-20',
      parent_meeting_required: false,
      acknowledge_conflicts: false,
    };

    function setupCreateMocks(settingsOverrides: Record<string, unknown> = {}) {
      mockRlsTx.behaviourIncident.findFirst.mockResolvedValue({
        id: INCIDENT_ID,
        tenant_id: TENANT_ID,
      });
      mockRlsTx.student.findFirst.mockResolvedValue({
        id: STUDENT_ID,
        tenant_id: TENANT_ID,
      });
      mockRlsTx.tenantSetting.findFirst.mockResolvedValue(makeSettings(settingsOverrides));
      mockRlsTx.schoolClosure.findFirst.mockResolvedValue(null);
      mockRlsTx.behaviourSanction.create.mockResolvedValue(makeSanction());
      mockRlsTx.behaviourSanction.findUnique.mockResolvedValue(makeSanction());
    }

    it('should throw NotFoundException when incident not found', async () => {
      mockRlsTx.behaviourIncident.findFirst.mockResolvedValue(null);
      mockRlsTx.student.findFirst.mockResolvedValue({ id: STUDENT_ID });
      mockRlsTx.tenantSetting.findFirst.mockResolvedValue(makeSettings());

      await expect(
        service.create(TENANT_ID, USER_ID, baseDto as Parameters<typeof service.create>[2]),
      ).rejects.toThrow(NotFoundException);
    });

    it('should throw NotFoundException when student not found', async () => {
      mockRlsTx.behaviourIncident.findFirst.mockResolvedValue({ id: INCIDENT_ID });
      mockRlsTx.student.findFirst.mockResolvedValue(null);
      mockRlsTx.tenantSetting.findFirst.mockResolvedValue(makeSettings());

      await expect(
        service.create(TENANT_ID, USER_ID, baseDto as Parameters<typeof service.create>[2]),
      ).rejects.toThrow(NotFoundException);
    });

    it('should set status to pending_approval when suspension_requires_approval is true for suspension', async () => {
      setupCreateMocks({ suspension_requires_approval: true });

      const dto = { ...baseDto, type: 'suspension_internal' as const };
      await service.create(TENANT_ID, USER_ID, dto as Parameters<typeof service.create>[2]);

      expect(mockRlsTx.behaviourSanction.create).toHaveBeenCalledWith({
        data: expect.objectContaining({ status: 'pending_approval' }),
      });
    });

    it('should set status to scheduled when suspension_requires_approval is false', async () => {
      setupCreateMocks({ suspension_requires_approval: false });

      const dto = { ...baseDto, type: 'suspension_internal' as const };
      await service.create(TENANT_ID, USER_ID, dto as Parameters<typeof service.create>[2]);

      expect(mockRlsTx.behaviourSanction.create).toHaveBeenCalledWith({
        data: expect.objectContaining({ status: 'scheduled' }),
      });
    });

    it('should set status to pending_approval for expulsion when expulsion_requires_approval is true', async () => {
      setupCreateMocks({ expulsion_requires_approval: true });

      const dto = { ...baseDto, type: 'expulsion' as const };
      await service.create(TENANT_ID, USER_ID, dto as Parameters<typeof service.create>[2]);

      expect(mockRlsTx.behaviourSanction.create).toHaveBeenCalledWith({
        data: expect.objectContaining({ status: 'pending_approval' }),
      });
    });

    it('should set status to scheduled for detention (no approval needed regardless)', async () => {
      setupCreateMocks({ suspension_requires_approval: true });

      await service.create(TENANT_ID, USER_ID, baseDto as Parameters<typeof service.create>[2]);

      expect(mockRlsTx.behaviourSanction.create).toHaveBeenCalledWith({
        data: expect.objectContaining({ status: 'scheduled' }),
      });
    });

    it('should compute suspension days for suspension types', async () => {
      setupCreateMocks();
      mockRlsTx.schoolClosure.findFirst.mockResolvedValue(null);

      const dto = {
        ...baseDto,
        type: 'suspension_internal' as const,
        suspension_start_date: '2026-03-16',
        suspension_end_date: '2026-03-20',
      };

      await service.create(TENANT_ID, USER_ID, dto as Parameters<typeof service.create>[2]);

      expect(mockRlsTx.behaviourSanction.create).toHaveBeenCalledWith({
        data: expect.objectContaining({ suspension_days: 5 }),
      });
    });

    it('should NOT compute suspension days for non-suspension types', async () => {
      setupCreateMocks();

      await service.create(TENANT_ID, USER_ID, baseDto as Parameters<typeof service.create>[2]);

      expect(mockRlsTx.behaviourSanction.create).toHaveBeenCalledWith({
        data: expect.objectContaining({ suspension_days: null }),
      });
    });

    it('should not fail creation when documentService is not available (Optional DI)', async () => {
      // documentService is @Optional() — test that creation works even without it
      setupCreateMocks({ document_auto_generate_detention_notice: true });

      const result = await service.create(
        TENANT_ID,
        USER_ID,
        baseDto as Parameters<typeof service.create>[2],
      );

      // Creation should succeed regardless of document generation
      expect(result).toBeDefined();
      expect(mockRlsTx.behaviourSanction.create).toHaveBeenCalled();
    });

    it('should not fail sanction creation when document generation throws', async () => {
      setupCreateMocks({ document_auto_generate_detention_notice: true });
      mockDocumentService.autoGenerateDocument.mockRejectedValue(new Error('Template not found'));

      const result = await service.create(
        TENANT_ID,
        USER_ID,
        baseDto as Parameters<typeof service.create>[2],
      );

      expect(result).toBeDefined();
    });

    it('should emit sanction parent notification after creation', async () => {
      setupCreateMocks();

      await service.create(TENANT_ID, USER_ID, baseDto as Parameters<typeof service.create>[2]);

      expect(mockSideEffects.emitSanctionParentNotification).toHaveBeenCalledWith(
        expect.objectContaining({
          tenant_id: TENANT_ID,
          sanction_id: SANCTION_ID,
          student_id: STUDENT_ID,
        }),
      );
    });

    it('should trigger exclusion case creation for external suspension with >=5 days', async () => {
      setupCreateMocks();
      mockRlsTx.schoolClosure.findFirst.mockResolvedValue(null);

      const dto = {
        ...baseDto,
        type: 'suspension_external' as const,
        suspension_start_date: '2026-03-16',
        suspension_end_date: '2026-03-20',
      };

      mockRlsTx.behaviourSanction.create.mockResolvedValue(
        makeSanction({ type: 'suspension_external', suspension_days: 5 }),
      );

      await service.create(TENANT_ID, USER_ID, dto as Parameters<typeof service.create>[2]);

      expect(mockSideEffects.emitCreateExclusionCase).toHaveBeenCalled();
    });

    it('should NOT trigger exclusion case for external suspension with <5 days', async () => {
      setupCreateMocks();
      // Simulate closure reducing days below threshold
      mockRlsTx.schoolClosure.findFirst.mockResolvedValue({ id: 'closure-1' });

      const dto = {
        ...baseDto,
        type: 'suspension_external' as const,
        suspension_start_date: '2026-03-16',
        suspension_end_date: '2026-03-17',
      };

      await service.create(TENANT_ID, USER_ID, dto as Parameters<typeof service.create>[2]);

      expect(mockSideEffects.emitCreateExclusionCase).not.toHaveBeenCalled();
    });

    it('should trigger exclusion case for expulsion regardless of suspension days', async () => {
      setupCreateMocks();

      const dto = {
        ...baseDto,
        type: 'expulsion' as const,
      };

      mockRlsTx.behaviourSanction.create.mockResolvedValue(makeSanction({ type: 'expulsion' }));

      await service.create(TENANT_ID, USER_ID, dto as Parameters<typeof service.create>[2]);

      expect(mockSideEffects.emitCreateExclusionCase).toHaveBeenCalled();
    });

    it('should NOT trigger exclusion case for detention type', async () => {
      setupCreateMocks();

      await service.create(TENANT_ID, USER_ID, baseDto as Parameters<typeof service.create>[2]);

      expect(mockSideEffects.emitCreateExclusionCase).not.toHaveBeenCalled();
    });

    it('should parse scheduled_start_time and scheduled_end_time when provided', async () => {
      setupCreateMocks();

      const dto = {
        ...baseDto,
        scheduled_start_time: '14:00:00',
        scheduled_end_time: '15:00:00',
      };

      await service.create(TENANT_ID, USER_ID, dto as Parameters<typeof service.create>[2]);

      expect(mockRlsTx.behaviourSanction.create).toHaveBeenCalledWith({
        data: expect.objectContaining({
          scheduled_start_time: expect.any(Date),
          scheduled_end_time: expect.any(Date),
        }),
      });
    });
  });

  // ─── createFromPolicy ──────────────────────────────────────────────────────

  describe('BehaviourSanctionsCrudService — createFromPolicy', () => {
    it('should return existing sanction if one already exists (dedup)', async () => {
      const existingSanction = makeSanction();
      mockRlsTx.behaviourSanction.findFirst.mockResolvedValue(existingSanction);

      const result = await service.createFromPolicy(
        TENANT_ID,
        {
          incident_id: INCIDENT_ID,
          student_id: STUDENT_ID,
          type: 'detention',
          scheduled_date: new Date('2026-03-20'),
          notes: null,
          created_by_id: USER_ID,
        },
        mockRlsTx as unknown as PrismaService,
      );

      expect(result).toEqual(existingSanction);
      expect(mockRlsTx.behaviourSanction.create).not.toHaveBeenCalled();
    });

    it('should create sanction when no duplicate exists', async () => {
      mockRlsTx.behaviourSanction.findFirst.mockResolvedValue(null);
      mockRlsTx.tenantSetting.findFirst.mockResolvedValue(makeSettings());
      mockRlsTx.behaviourSanction.create.mockResolvedValue(makeSanction());

      await service.createFromPolicy(
        TENANT_ID,
        {
          incident_id: INCIDENT_ID,
          student_id: STUDENT_ID,
          type: 'detention',
          scheduled_date: new Date('2026-03-20'),
          notes: 'Auto from policy',
          created_by_id: USER_ID,
        },
        mockRlsTx as unknown as PrismaService,
      );

      expect(mockRlsTx.behaviourSanction.create).toHaveBeenCalled();
      expect(mockHistory.recordHistory).toHaveBeenCalledWith(
        mockRlsTx,
        TENANT_ID,
        'sanction',
        SANCTION_ID,
        USER_ID,
        'created',
        null,
        expect.objectContaining({ source: 'policy_engine' }),
      );
    });
  });

  // ─── getById ───────────────────────────────────────────────────────────────

  describe('BehaviourSanctionsCrudService — getById', () => {
    it('should throw NotFoundException when sanction not found', async () => {
      mockPrisma.behaviourSanction.findFirst.mockResolvedValue(null);

      await expect(service.getById(TENANT_ID, 'nonexistent')).rejects.toThrow(NotFoundException);
    });

    it('should return sanction with includes when found', async () => {
      mockPrisma.behaviourSanction.findFirst.mockResolvedValue(makeSanction());

      const result = await service.getById(TENANT_ID, SANCTION_ID);

      expect(result.id).toBe(SANCTION_ID);
    });
  });

  // ─── list ──────────────────────────────────────────────────────────────────

  describe('BehaviourSanctionsCrudService — list', () => {
    const baseQuery = {
      page: 1,
      pageSize: 20,
    };

    it('should apply student_id filter', async () => {
      mockPrisma.behaviourSanction.findMany.mockResolvedValue([]);
      mockPrisma.behaviourSanction.count.mockResolvedValue(0);

      await service.list(TENANT_ID, {
        ...baseQuery,
        student_id: STUDENT_ID,
      } as Parameters<typeof service.list>[1]);

      expect(mockPrisma.behaviourSanction.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({ student_id: STUDENT_ID }),
        }),
      );
    });

    it('should apply type filter', async () => {
      mockPrisma.behaviourSanction.findMany.mockResolvedValue([]);
      mockPrisma.behaviourSanction.count.mockResolvedValue(0);

      await service.list(TENANT_ID, {
        ...baseQuery,
        type: 'detention',
      } as Parameters<typeof service.list>[1]);

      expect(mockPrisma.behaviourSanction.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({ type: 'detention' }),
        }),
      );
    });

    it('should apply date_from and date_to filters', async () => {
      mockPrisma.behaviourSanction.findMany.mockResolvedValue([]);
      mockPrisma.behaviourSanction.count.mockResolvedValue(0);

      await service.list(TENANT_ID, {
        ...baseQuery,
        date_from: '2026-01-01',
        date_to: '2026-12-31',
      } as Parameters<typeof service.list>[1]);

      expect(mockPrisma.behaviourSanction.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({
            scheduled_date: { gte: expect.any(Date), lte: expect.any(Date) },
          }),
        }),
      );
    });

    it('should apply status and supervised_by_id and incident_id filters', async () => {
      mockPrisma.behaviourSanction.findMany.mockResolvedValue([]);
      mockPrisma.behaviourSanction.count.mockResolvedValue(0);

      await service.list(TENANT_ID, {
        ...baseQuery,
        status: 'scheduled',
        supervised_by_id: USER_ID,
        incident_id: INCIDENT_ID,
      } as Parameters<typeof service.list>[1]);

      expect(mockPrisma.behaviourSanction.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({
            status: 'scheduled',
            supervised_by_id: USER_ID,
            incident_id: INCIDENT_ID,
          }),
        }),
      );
    });
  });

  // ─── update ────────────────────────────────────────────────────────────────

  describe('BehaviourSanctionsCrudService — update', () => {
    it('should throw NotFoundException when sanction not found', async () => {
      mockRlsTx.behaviourSanction.findFirst.mockResolvedValue(null);

      await expect(
        service.update(TENANT_ID, SANCTION_ID, { notes: 'Updated' }, USER_ID),
      ).rejects.toThrow(NotFoundException);
    });

    it('should return sanction unchanged when no values differ', async () => {
      mockRlsTx.behaviourSanction.findFirst.mockResolvedValue(makeSanction({ notes: 'Same' }));

      const result = await service.update(
        TENANT_ID,
        SANCTION_ID,
        { notes: 'Same' } as Parameters<typeof service.update>[2],
        USER_ID,
      );

      expect(result).toEqual(makeSanction({ notes: 'Same' }));
      expect(mockRlsTx.behaviourSanction.update).not.toHaveBeenCalled();
    });

    it('should create amendment notice when parent-visible field changes', async () => {
      mockRlsTx.behaviourSanction.findFirst.mockResolvedValue(
        makeSanction({ scheduled_date: new Date('2026-03-20') }),
      );
      mockRlsTx.behaviourSanction.update.mockResolvedValue(makeSanction());
      mockRlsTx.behaviourAmendmentNotice.create.mockResolvedValue({ id: 'amend-1' });

      await service.update(
        TENANT_ID,
        SANCTION_ID,
        { scheduled_date: '2026-03-25' } as Parameters<typeof service.update>[2],
        USER_ID,
      );

      expect(mockRlsTx.behaviourAmendmentNotice.create).toHaveBeenCalledWith({
        data: expect.objectContaining({
          entity_type: 'sanction',
          entity_id: SANCTION_ID,
          amendment_type: 'correction',
        }),
      });
    });

    it('should NOT create amendment notice when non-parent-visible field changes', async () => {
      mockRlsTx.behaviourSanction.findFirst.mockResolvedValue(makeSanction({ notes: 'Old notes' }));
      mockRlsTx.behaviourSanction.update.mockResolvedValue(makeSanction());

      await service.update(
        TENANT_ID,
        SANCTION_ID,
        { notes: 'New notes' } as Parameters<typeof service.update>[2],
        USER_ID,
      );

      expect(mockRlsTx.behaviourAmendmentNotice.create).not.toHaveBeenCalled();
    });
  });
});
