'use client';

import {
  Button,
  Checkbox,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Input,
  Label,
  RadioGroup,
  RadioGroupItem,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  toast,
} from '@school/ui';
import { AlertTriangle, Minus, Plus, Wand2 } from 'lucide-react';
import { useTranslations } from 'next-intl';
import * as React from 'react';

import { apiClient } from '@/lib/api-client';

// ─── Types ────────────────────────────────────────────────────────────────────

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  academicYearId: string;
  yearGroupId: string;
  onGenerated: () => void;
}

interface DurationGroup {
  id: string;
  duration: number;
  count: number;
}

interface GeneratedPeriod {
  period_name: string;
  start_time: string;
  end_time: string;
  schedule_period_type: 'teaching' | 'break_supervision' | 'lunch_duty';
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function timeToMinutes(time: string): number {
  const [h, m] = time.split(':').map(Number);
  return (h ?? 0) * 60 + (m ?? 0);
}

function minutesToTime(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
}

let nextGroupId = 0;
function generateGroupId(): string {
  nextGroupId += 1;
  return `group-${nextGroupId}`;
}

// ─── Constants ────────────────────────────────────────────────────────────────

const WEEKDAYS = [1, 2, 3, 4, 5, 6, 0] as const;
const WEEKDAY_KEYS: Record<number, string> = {
  0: 'sunday',
  1: 'monday',
  2: 'tuesday',
  3: 'wednesday',
  4: 'thursday',
  5: 'friday',
  6: 'saturday',
};

const DURATION_PRESETS = [40, 45, 60, 90, 120] as const;
const SMALL_BREAK_PRESETS = [10, 15, 20] as const;
const MAIN_BREAK_PRESETS = [30, 45, 60] as const;

const PERIOD_TYPE_COLORS: Record<string, string> = {
  teaching:
    'bg-blue-50 border-blue-200 text-blue-700 dark:bg-blue-950 dark:border-blue-800 dark:text-blue-300',
  break_supervision:
    'bg-amber-50 border-amber-200 text-amber-700 dark:bg-amber-950 dark:border-amber-800 dark:text-amber-300',
  lunch_duty:
    'bg-orange-50 border-orange-200 text-orange-700 dark:bg-orange-950 dark:border-orange-800 dark:text-orange-300',
};

// ─── Generation Algorithm ─────────────────────────────────────────────────────

function generatePeriods(opts: {
  startTime: string;
  endTime: string;
  mode: 'uniform' | 'mixed';
  uniformDuration: number;
  durationGroups: DurationGroup[];
  hasSmallBreak: boolean;
  smallBreakAfter: number;
  smallBreakDuration: number;
  hasMainBreak: boolean;
  mainBreakAfter: number;
  mainBreakDuration: number;
}): GeneratedPeriod[] {
  const startMin = timeToMinutes(opts.startTime);
  const endMin = timeToMinutes(opts.endTime);

  if (endMin <= startMin) return [];

  // Build ordered list of teaching durations
  let durations: number[];
  if (opts.mode === 'uniform') {
    const totalBreakTime =
      (opts.hasSmallBreak ? opts.smallBreakDuration : 0) +
      (opts.hasMainBreak ? opts.mainBreakDuration : 0);
    const availableTime = endMin - startMin - totalBreakTime;
    if (availableTime <= 0) return [];
    const count = Math.floor(availableTime / opts.uniformDuration);
    durations = Array(count).fill(opts.uniformDuration) as number[];
  } else {
    durations = [];
    for (const group of opts.durationGroups) {
      for (let i = 0; i < group.count; i++) {
        durations.push(group.duration);
      }
    }
  }

  if (durations.length === 0) return [];

  const result: GeneratedPeriod[] = [];
  let currentTime = startMin;
  let teachingIndex = 0;

  for (const duration of durations) {
    // Insert small break before this teaching period
    if (opts.hasSmallBreak && teachingIndex === opts.smallBreakAfter) {
      const breakEnd = currentTime + opts.smallBreakDuration;
      if (breakEnd > endMin) break;
      result.push({
        period_name: 'Break',
        start_time: minutesToTime(currentTime),
        end_time: minutesToTime(breakEnd),
        schedule_period_type: 'break_supervision',
      });
      currentTime = breakEnd;
    }

    // Insert main break before this teaching period
    if (opts.hasMainBreak && teachingIndex === opts.mainBreakAfter) {
      const breakEnd = currentTime + opts.mainBreakDuration;
      if (breakEnd > endMin) break;
      result.push({
        period_name: 'Lunch',
        start_time: minutesToTime(currentTime),
        end_time: minutesToTime(breakEnd),
        schedule_period_type: 'lunch_duty',
      });
      currentTime = breakEnd;
    }

    // Check if teaching period fits
    if (currentTime + duration > endMin) break;

    teachingIndex++;
    result.push({
      period_name: `Period ${teachingIndex}`,
      start_time: minutesToTime(currentTime),
      end_time: minutesToTime(currentTime + duration),
      schedule_period_type: 'teaching',
    });
    currentTime += duration;
  }

  // Handle breaks that come after all teaching periods (edge case)
  if (opts.hasSmallBreak && teachingIndex === opts.smallBreakAfter) {
    const breakEnd = currentTime + opts.smallBreakDuration;
    if (breakEnd <= endMin) {
      result.push({
        period_name: 'Break',
        start_time: minutesToTime(currentTime),
        end_time: minutesToTime(breakEnd),
        schedule_period_type: 'break_supervision',
      });
      currentTime = breakEnd;
    }
  }
  if (opts.hasMainBreak && teachingIndex === opts.mainBreakAfter) {
    const breakEnd = currentTime + opts.mainBreakDuration;
    if (breakEnd <= endMin) {
      result.push({
        period_name: 'Lunch',
        start_time: minutesToTime(currentTime),
        end_time: minutesToTime(breakEnd),
        schedule_period_type: 'lunch_duty',
      });
    }
  }

  return result;
}

// ─── Component ────────────────────────────────────────────────────────────────

export function AutoGenerateDialog({
  open,
  onOpenChange,
  academicYearId,
  yearGroupId,
  onGenerated,
}: AutoGenerateDialogProps) {
  const tv = useTranslations('scheduling.v2');
  const ts = useTranslations('scheduling');
  const tc = useTranslations('common');

  // Form state
  const [weekday, setWeekday] = React.useState(1);
  const [startTime, setStartTime] = React.useState('08:00');
  const [endTime, setEndTime] = React.useState('15:00');
  const [durationMode, setDurationMode] = React.useState<'uniform' | 'mixed'>('uniform');
  const [uniformPreset, setUniformPreset] = React.useState<number | 'custom'>(45);
  const [uniformCustom, setUniformCustom] = React.useState(45);
  const [durationGroups, setDurationGroups] = React.useState<DurationGroup[]>([
    { id: generateGroupId(), duration: 60, count: 3 },
  ]);

  const [hasSmallBreak, setHasSmallBreak] = React.useState(true);
  const [smallBreakAfter, setSmallBreakAfter] = React.useState(2);
  const [smallBreakDuration, setSmallBreakDuration] = React.useState(15);

  const [hasMainBreak, setHasMainBreak] = React.useState(true);
  const [mainBreakAfter, setMainBreakAfter] = React.useState(4);
  const [mainBreakDuration, setMainBreakDuration] = React.useState(30);

  const [isApplying, setIsApplying] = React.useState(false);

  const uniformDuration = uniformPreset === 'custom' ? uniformCustom : uniformPreset;

  // Generate preview
  const preview = React.useMemo(
    () =>
      generatePeriods({
        startTime,
        endTime,
        mode: durationMode,
        uniformDuration,
        durationGroups,
        hasSmallBreak,
        smallBreakAfter,
        smallBreakDuration,
        hasMainBreak,
        mainBreakAfter,
        mainBreakDuration,
      }),
    [
      startTime,
      endTime,
      durationMode,
      uniformDuration,
      durationGroups,
      hasSmallBreak,
      smallBreakAfter,
      smallBreakDuration,
      hasMainBreak,
      mainBreakAfter,
      mainBreakDuration,
    ],
  );

  // Stats
  const teachingPeriods = preview.filter((p) => p.schedule_period_type === 'teaching');
  const breakPeriods = preview.filter((p) => p.schedule_period_type !== 'teaching');
  const totalTeachingMin = teachingPeriods.reduce(
    (sum, p) => sum + timeToMinutes(p.end_time) - timeToMinutes(p.start_time),
    0,
  );
  const totalBreakMin = breakPeriods.reduce(
    (sum, p) => sum + timeToMinutes(p.end_time) - timeToMinutes(p.start_time),
    0,
  );
  const lastPeriodEnd =
    preview.length > 0 ? timeToMinutes(preview[preview.length - 1]!.end_time) : timeToMinutes(startTime);
  const remainingMin = timeToMinutes(endTime) - lastPeriodEnd;

  // Duration group management
  const addDurationGroup = () => {
    setDurationGroups((prev) => [...prev, { id: generateGroupId(), duration: 45, count: 1 }]);
  };

  const removeDurationGroup = (id: string) => {
    setDurationGroups((prev) => prev.filter((g) => g.id !== id));
  };

  const updateDurationGroup = (id: string, field: 'duration' | 'count', value: number) => {
    setDurationGroups((prev) =>
      prev.map((g) => (g.id === id ? { ...g, [field]: value } : g)),
    );
  };

  // Apply handler
  const handleApply = async () => {
    if (preview.length === 0) return;
    setIsApplying(true);
    try {
      await apiClient('/api/v1/period-grid/replace-day', {
        method: 'POST',
        body: JSON.stringify({
          academic_year_id: academicYearId,
          year_group_id: yearGroupId,
          weekday,
          periods: preview.map((p) => ({
            period_name: p.period_name,
            start_time: p.start_time,
            end_time: p.end_time,
            schedule_period_type: p.schedule_period_type,
          })),
        }),
      });
      toast.success(tv('generatedSuccessfully'));
      onOpenChange(false);
      onGenerated();
    } catch {
      toast.error(tc('errorGeneric'));
    } finally {
      setIsApplying(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="h-5 w-5" />
            {tv('autoGenerateTitle')}
          </DialogTitle>
          <p className="text-sm text-text-tertiary">{tv('autoGenerateDesc')}</p>
        </DialogHeader>

        <div className="space-y-5">
          {/* Day of week */}
          <div className="space-y-1.5">
            <Label>{ts('weekday')}</Label>
            <Select value={String(weekday)} onValueChange={(v) => setWeekday(Number(v))}>
              <SelectTrigger className="w-full sm:w-48">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {WEEKDAYS.map((d) => (
                  <SelectItem key={d} value={String(d)}>
                    {ts(WEEKDAY_KEYS[d]!)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* School times */}
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label>{tv('schoolStartTime')}</Label>
              <Input
                type="time"
                value={startTime}
                onChange={(e) => setStartTime(e.target.value)}
                className="w-full"
              />
            </div>
            <div className="space-y-1.5">
              <Label>{tv('schoolEndTime')}</Label>
              <Input
                type="time"
                value={endTime}
                onChange={(e) => setEndTime(e.target.value)}
                className="w-full"
              />
            </div>
          </div>

          {/* Period Duration Mode */}
          <div className="space-y-3">
            <Label>{tv('periodDuration')}</Label>
            <RadioGroup
              value={durationMode}
              onValueChange={(v) => setDurationMode(v as 'uniform' | 'mixed')}
              className="flex flex-col gap-2 sm:flex-row sm:gap-4"
            >
              <div className="flex items-center gap-2">
                <RadioGroupItem value="uniform" id="mode-uniform" />
                <Label htmlFor="mode-uniform" className="cursor-pointer font-normal">
                  {tv('uniformDuration')}
                </Label>
              </div>
              <div className="flex items-center gap-2">
                <RadioGroupItem value="mixed" id="mode-mixed" />
                <Label htmlFor="mode-mixed" className="cursor-pointer font-normal">
                  {tv('mixedDuration')}
                </Label>
              </div>
            </RadioGroup>

            {durationMode === 'uniform' && (
              <div className="flex flex-wrap items-end gap-2">
                {DURATION_PRESETS.map((preset) => (
                  <Button
                    key={preset}
                    type="button"
                    variant={uniformPreset === preset ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setUniformPreset(preset)}
                  >
                    {preset} {tv('minutes')}
                  </Button>
                ))}
                <Button
                  type="button"
                  variant={uniformPreset === 'custom' ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setUniformPreset('custom')}
                >
                  {tv('durationPresets.custom')}
                </Button>
                {uniformPreset === 'custom' && (
                  <Input
                    type="number"
                    min={10}
                    max={180}
                    value={uniformCustom}
                    onChange={(e) => setUniformCustom(Math.max(1, Number(e.target.value)))}
                    className="w-full sm:w-24"
                    placeholder={tv('customDuration')}
                  />
                )}
              </div>
            )}

            {durationMode === 'mixed' && (
              <div className="space-y-2">
                {durationGroups.map((group) => (
                  <div key={group.id} className="flex flex-wrap items-center gap-2">
                    <Input
                      type="number"
                      min={1}
                      max={20}
                      value={group.count}
                      onChange={(e) =>
                        updateDurationGroup(group.id, 'count', Math.max(1, Number(e.target.value)))
                      }
                      className="w-full sm:w-16"
                    />
                    <span className="text-sm text-text-secondary">&times;</span>
                    <Input
                      type="number"
                      min={10}
                      max={180}
                      value={group.duration}
                      onChange={(e) =>
                        updateDurationGroup(group.id, 'duration', Math.max(1, Number(e.target.value)))
                      }
                      className="w-full sm:w-20"
                    />
                    <span className="text-sm text-text-secondary">{tv('minutes')}</span>
                    {durationGroups.length > 1 && (
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        className="text-red-500 hover:text-red-600"
                        onClick={() => removeDurationGroup(group.id)}
                      >
                        <Minus className="me-1 h-3 w-3" />
                        {tv('removeDurationGroup')}
                      </Button>
                    )}
                  </div>
                ))}
                <Button type="button" variant="outline" size="sm" onClick={addDurationGroup}>
                  <Plus className="me-1 h-3 w-3" />
                  {tv('addDurationGroup')}
                </Button>
              </div>
            )}
          </div>

          {/* Break Configuration */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {/* Small Break */}
            <div className="space-y-2 rounded-lg border p-3">
              <div className="flex items-center gap-2">
                <Checkbox
                  id="small-break"
                  checked={hasSmallBreak}
                  onCheckedChange={(v) => setHasSmallBreak(v === true)}
                />
                <Label htmlFor="small-break" className="cursor-pointer font-medium">
                  {tv('smallBreak')}
                </Label>
              </div>
              {hasSmallBreak && (
                <div className="space-y-2 ps-6">
                  <div className="space-y-1">
                    <Label className="text-xs">{tv('smallBreakAfter')}</Label>
                    <Input
                      type="number"
                      min={1}
                      max={20}
                      value={smallBreakAfter}
                      onChange={(e) => setSmallBreakAfter(Math.max(1, Number(e.target.value)))}
                      className="w-full sm:w-20"
                    />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs">{tv('smallBreakDuration')}</Label>
                    <div className="flex flex-wrap gap-1">
                      {SMALL_BREAK_PRESETS.map((preset) => (
                        <Button
                          key={preset}
                          type="button"
                          variant={smallBreakDuration === preset ? 'default' : 'outline'}
                          size="sm"
                          className="h-7 text-xs"
                          onClick={() => setSmallBreakDuration(preset)}
                        >
                          {preset} {tv('minutes')}
                        </Button>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Main Break */}
            <div className="space-y-2 rounded-lg border p-3">
              <div className="flex items-center gap-2">
                <Checkbox
                  id="main-break"
                  checked={hasMainBreak}
                  onCheckedChange={(v) => setHasMainBreak(v === true)}
                />
                <Label htmlFor="main-break" className="cursor-pointer font-medium">
                  {tv('mainBreak')}
                </Label>
              </div>
              {hasMainBreak && (
                <div className="space-y-2 ps-6">
                  <div className="space-y-1">
                    <Label className="text-xs">{tv('mainBreakAfter')}</Label>
                    <Input
                      type="number"
                      min={1}
                      max={20}
                      value={mainBreakAfter}
                      onChange={(e) => setMainBreakAfter(Math.max(1, Number(e.target.value)))}
                      className="w-full sm:w-20"
                    />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs">{tv('mainBreakDuration')}</Label>
                    <div className="flex flex-wrap gap-1">
                      {MAIN_BREAK_PRESETS.map((preset) => (
                        <Button
                          key={preset}
                          type="button"
                          variant={mainBreakDuration === preset ? 'default' : 'outline'}
                          size="sm"
                          className="h-7 text-xs"
                          onClick={() => setMainBreakDuration(preset)}
                        >
                          {preset} {tv('minutes')}
                        </Button>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Live Preview */}
          <div className="space-y-2">
            <Label className="text-sm font-semibold">{tv('preview')}</Label>

            {preview.length === 0 ? (
              <div className="flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 dark:border-amber-700 dark:bg-amber-900/20">
                <AlertTriangle className="h-4 w-4 shrink-0 text-amber-600" />
                <span className="text-sm text-amber-800 dark:text-amber-300">
                  {tv('noPeriodsGenerated')}
                </span>
              </div>
            ) : (
              <>
                {/* Period rows */}
                <div className="space-y-1 rounded-lg border p-2">
                  {preview.map((period, idx) => (
                    <div
                      key={idx}
                      className={`flex items-center gap-2 rounded px-3 py-1.5 text-sm border ${
                        PERIOD_TYPE_COLORS[period.schedule_period_type] ?? ''
                      }`}
                    >
                      <span className="min-w-0 flex-1 truncate font-medium">
                        {period.period_name}
                      </span>
                      <span className="shrink-0 font-mono text-xs opacity-70">
                        {period.start_time} - {period.end_time}
                      </span>
                    </div>
                  ))}
                </div>

                {/* Stats */}
                <div className="flex flex-wrap gap-4 text-xs text-text-secondary">
                  <span>
                    {teachingPeriods.length} {tv('periodsCount')} &middot; {tv('totalTeaching')}:{' '}
                    {totalTeachingMin} {tv('minutes')}
                  </span>
                  <span>
                    {tv('totalBreak')}: {totalBreakMin} {tv('minutes')}
                  </span>
                  {remainingMin > 0 && (
                    <span className="text-amber-600">
                      {remainingMin} {tv('minutes')} {tv('remainingTime')}
                    </span>
                  )}
                </div>
              </>
            )}
          </div>
        </div>

        <DialogFooter className="gap-2 sm:gap-0">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            {tc('cancel')}
          </Button>
          <Button
            onClick={() => void handleApply()}
            disabled={isApplying || preview.length === 0}
          >
            {isApplying ? '...' : tv('applyToDay')}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
