/* eslint-disable import/order -- jest.mock must precede mocked imports */
import { NotFoundException } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { getQueueToken } from '@nestjs/bullmq';

jest.mock('../../../common/middleware/rls.middleware', () => ({
  createRlsClient: (_prisma: unknown) => ({
    $transaction: async (fn: (tx: unknown) => Promise<unknown>) => fn(_prisma),
  }),
}));

import { MOCK_FACADE_PROVIDERS } from '../mock-facades';
import { BehaviourSanctionsService } from '../../../modules/behaviour/behaviour-sanctions.service';
import { BehaviourService } from '../../../modules/behaviour/behaviour.service';
import { BehaviourDocumentService } from '../../../modules/behaviour/behaviour-document.service';
import { BehaviourHistoryService } from '../../../modules/behaviour/behaviour-history.service';
import { BehaviourScopeService } from '../../../modules/behaviour/behaviour-scope.service';
import { PrismaService } from '../../../modules/prisma/prisma.service';
import { BehaviourSideEffectsService } from '../../../modules/behaviour/behaviour-side-effects.service';
import { SequenceService } from '../../../modules/sequence/sequence.service';

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const TENANT_ID = 'tenant-uuid-integration-002';
const USER_ID = 'user-uuid-integration-002';
const STUDENT_ID = 'student-uuid-integration-002';
const INCIDENT_ID = 'incident-uuid-integration-002';
const CATEGORY_ID = 'category-uuid-integration-002';
const ACADEMIC_YEAR_ID = 'ay-uuid-integration-002';
const SANCTION_ID = 'sanction-uuid-integration-002';

// ─── Mock factories ──────────────────────────────────────────────────────────

const buildMockPrisma = () => ({
  behaviourIncident: {
    findFirst: jest.fn(),
    create: jest.fn(),
    findUnique: jest.fn(),
    update: jest.fn(),
  },
  behaviourIncidentParticipant: {
    create: jest.fn(),
    findMany: jest.fn(),
  },
  behaviourCategory: {
    findFirst: jest.fn(),
  },
  behaviourSanction: {
    findFirst: jest.fn(),
    create: jest.fn(),
    findUnique: jest.fn(),
  },
  behaviourTask: {
    create: jest.fn(),
  },
  student: {
    findMany: jest.fn(),
    findFirst: jest.fn(),
  },
  user: {
    findUnique: jest.fn(),
  },
  academicYear: {
    findUnique: jest.fn(),
  },
  academicPeriod: {
    findUnique: jest.fn(),
  },
  subject: {
    findUnique: jest.fn(),
  },
  room: {
    findUnique: jest.fn(),
  },
  tenantConfig: {
    findFirst: jest.fn(),
  },
  tenantSetting: {
    findFirst: jest.fn(),
    findMany: jest.fn(),
  },
  schoolClosure: {
    findMany: jest.fn(),
  },
});

const mockQueue = {
  add: jest.fn().mockResolvedValue({ id: 'job-1' }),
};

// ─── Test Suite ──────────────────────────────────────────────────────────────

describe('Incident -> Sanction -> Notification flow', () => {
  let behaviourService: BehaviourService;
  let sanctionsService: BehaviourSanctionsService;
  let mockPrisma: ReturnType<typeof buildMockPrisma>;

  const mockSequenceService = {
    nextNumber: jest.fn(),
  };

  const mockHistoryService = {
    recordHistory: jest.fn(),
  };

  const mockScopeService = {
    applyVisibilityFilter: jest.fn(),
    checkStudentAccess: jest.fn(),
  };

  const mockDocumentService = {
    autoGenerateDocument: jest.fn(),
  };

  const mockSideEffectsService = {
    emitParentNotification: jest.fn(),
    emitPolicyEvaluation: jest.fn(),
    emitCheckAwards: jest.fn(),
    emitSanctionParentNotification: jest.fn(),
    emitCreateExclusionCase: jest.fn(),
  };

  beforeEach(async () => {
    mockPrisma = buildMockPrisma();

    const module = await Test.createTestingModule({
      providers: [
        ...MOCK_FACADE_PROVIDERS,
        BehaviourService,
        BehaviourSanctionsService,
        { provide: PrismaService, useValue: mockPrisma },
        { provide: SequenceService, useValue: mockSequenceService },
        { provide: BehaviourHistoryService, useValue: mockHistoryService },
        { provide: BehaviourScopeService, useValue: mockScopeService },
        { provide: BehaviourDocumentService, useValue: mockDocumentService },
        { provide: BehaviourSideEffectsService, useValue: mockSideEffectsService },
        { provide: getQueueToken('notifications'), useValue: mockQueue },
        { provide: getQueueToken('behaviour'), useValue: mockQueue },
      ],
    }).compile();

    behaviourService = module.get(BehaviourService);
    sanctionsService = module.get(BehaviourSanctionsService);
  });

  afterEach(() => jest.clearAllMocks());

  it('should create an incident with participants and enqueue parent notification when category requires it', async () => {
    // Setup: active category that requires parent notification
    mockPrisma.behaviourCategory.findFirst.mockResolvedValue({
      id: CATEGORY_ID,
      tenant_id: TENANT_ID,
      name: 'Disruption',
      polarity: 'negative',
      severity: 'moderate',
      point_value: -2,
      is_active: true,
      requires_parent_notification: true,
      requires_follow_up: false,
      parent_visible: true,
      benchmark_category: null,
    });

    // Setup: valid student
    mockPrisma.student.findMany.mockResolvedValue([
      {
        id: STUDENT_ID,
        first_name: 'Test',
        last_name: 'Student',
        year_group: { id: 'yg-1', name: 'Year 5' },
        class_enrolments: [{ class_entity: { name: 'Class 5A' } }],
      },
    ]);

    // Setup: reporter user
    mockPrisma.user.findUnique.mockResolvedValue({
      id: USER_ID,
      first_name: 'John',
      last_name: 'Teacher',
    });

    mockSequenceService.nextNumber.mockResolvedValue('BH-202604-000001');

    const createdIncident = {
      id: INCIDENT_ID,
      tenant_id: TENANT_ID,
      incident_number: 'BH-202604-000001',
      status: 'active',
      parent_notification_status: 'pending',
      follow_up_required: false,
      participants: [{ student_id: STUDENT_ID, role: 'subject', points_awarded: -2 }],
    };
    mockPrisma.behaviourIncident.create.mockResolvedValue(createdIncident);
    mockPrisma.behaviourIncidentParticipant.create.mockResolvedValue({});
    // The service returns findUnique at the end of the transaction
    mockPrisma.behaviourIncident.findUnique.mockResolvedValue({
      ...createdIncident,
      category: { id: CATEGORY_ID, name: 'Disruption' },
    });

    const result = await behaviourService.createIncident(TENANT_ID, USER_ID, {
      category_id: CATEGORY_ID,
      description: 'Student was disruptive during class',
      context_type: 'class',
      student_ids: [STUDENT_ID],
      occurred_at: '2026-04-01T10:00:00Z',
      auto_submit: true,
      academic_year_id: ACADEMIC_YEAR_ID,
    });

    expect(result).toBeDefined();
    // Incident created with correct status
    expect(mockPrisma.behaviourIncident.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          tenant_id: TENANT_ID,
          status: 'active',
          parent_notification_status: 'pending',
        }),
      }),
    );
    // Participant created for student
    expect(mockPrisma.behaviourIncidentParticipant.create).toHaveBeenCalled();
  });

  it('should create a sanction linked to an incident and enqueue parent notification', async () => {
    // Setup: incident exists
    mockPrisma.behaviourIncident.findFirst.mockResolvedValue({
      id: INCIDENT_ID,
      tenant_id: TENANT_ID,
    });

    // Setup: student exists
    mockPrisma.student.findFirst.mockResolvedValue({
      id: STUDENT_ID,
      tenant_id: TENANT_ID,
    });

    // Setup: behaviour settings — no approval needed for detention
    mockPrisma.tenantSetting.findFirst.mockResolvedValue({
      settings: { behaviour: {} },
    });

    mockSequenceService.nextNumber.mockResolvedValue('SN-202604-000001');

    const createdSanction = {
      id: SANCTION_ID,
      tenant_id: TENANT_ID,
      sanction_number: 'SN-202604-000001',
      incident_id: INCIDENT_ID,
      student_id: STUDENT_ID,
      type: 'detention',
      status: 'scheduled',
    };
    mockPrisma.behaviourSanction.create.mockResolvedValue(createdSanction);
    mockPrisma.behaviourSanction.findUnique.mockResolvedValue({
      ...createdSanction,
      incident: { id: INCIDENT_ID, incident_number: 'BH-202604-000001' },
      student: { id: STUDENT_ID, first_name: 'Test', last_name: 'Student' },
      supervised_by: null,
    });

    const result = await sanctionsService.create(TENANT_ID, USER_ID, {
      incident_id: INCIDENT_ID,
      student_id: STUDENT_ID,
      type: 'detention',
      scheduled_date: '2026-04-03',
      parent_meeting_required: false,
      acknowledge_conflicts: false,
    });

    expect(result).toBeDefined();
    // Sanction created for the right incident and student
    expect(mockPrisma.behaviourSanction.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          tenant_id: TENANT_ID,
          incident_id: INCIDENT_ID,
          student_id: STUDENT_ID,
          type: 'detention',
          status: 'scheduled',
        }),
      }),
    );
    // Parent notification enqueued via side effects service
    expect(mockSideEffectsService.emitSanctionParentNotification).toHaveBeenCalledWith(
      expect.objectContaining({
        tenant_id: TENANT_ID,
        sanction_id: SANCTION_ID,
        student_id: STUDENT_ID,
      }),
    );
    // History recorded
    expect(mockHistoryService.recordHistory).toHaveBeenCalledWith(
      expect.anything(),
      TENANT_ID,
      'sanction',
      SANCTION_ID,
      USER_ID,
      'created',
      null,
      expect.objectContaining({
        status: 'scheduled',
        type: 'detention',
      }),
    );
  });

  it('should throw when creating a sanction for a non-existent incident', async () => {
    mockPrisma.behaviourIncident.findFirst.mockResolvedValue(null);

    await expect(
      sanctionsService.create(TENANT_ID, USER_ID, {
        incident_id: 'non-existent',
        student_id: STUDENT_ID,
        type: 'detention',
        scheduled_date: '2026-04-03',
        parent_meeting_required: false,
        acknowledge_conflicts: false,
      }),
    ).rejects.toThrow(NotFoundException);
  });
});
