/**
 * Default behaviour categories seeded by the wellbeing rebuild
 * (Implementation 01). Twenty-eight categories mapped across positive and
 * negative polarity, three severity tiers (minor / moderate / major) and
 * the `benchmark_category` enum used for cross-tenant analytics.
 *
 * These defaults only apply to tenants that currently have ZERO
 * behaviour_categories rows (see `seedWellbeingDefaultsForTenant`). New
 * tenants bootstrapped through `seedBehaviourData` continue to receive
 * the legacy 12-category seed (sanction-outcome model); the two seed
 * paths are intentionally distinct for now. A future rebuild wave can
 * reconcile them once the 28-category behavioural taxonomy is proven in
 * production.
 */
import type { Prisma } from '@prisma/client';

/**
 * Severity & benchmark mapping:
 *   positive minor (1 pt) → severity 1, benchmark 'minor_positive'
 *   positive moderate (3 pt) → severity 3, benchmark 'merit'
 *   positive major (5 pt) → severity 5, benchmark 'major_positive'
 *   negative minor (1 pt) → severity 2, benchmark 'verbal_warning'
 *   negative moderate (3 pt) → severity 4, benchmark 'written_warning'
 *   negative major (5 pt) → severity 7, benchmark 'external_suspension'
 */
export type WellbeingDefaultCategorySeed = Omit<
  Prisma.BehaviourCategoryCreateManyInput,
  'id' | 'tenant_id' | 'created_at' | 'updated_at'
>;

export const DEFAULT_BEHAVIOUR_CATEGORIES: WellbeingDefaultCategorySeed[] = [
  // ─── Negative — minor (severity 2, 1 pt) ─────────────────────────────────
  {
    name: 'Lateness',
    name_ar: 'التأخر',
    polarity: 'negative',
    severity: 2,
    point_value: 1,
    color: '#f59e0b',
    icon: 'clock',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'verbal_warning',
    display_order: 100,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Uniform infringement',
    name_ar: 'مخالفة الزي',
    polarity: 'negative',
    severity: 2,
    point_value: 1,
    color: '#f59e0b',
    icon: 'shirt',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'verbal_warning',
    display_order: 101,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Phone use',
    name_ar: 'استخدام الهاتف',
    polarity: 'negative',
    severity: 2,
    point_value: 1,
    color: '#f59e0b',
    icon: 'smartphone',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'verbal_warning',
    display_order: 102,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Out of bounds',
    name_ar: 'خارج الحدود',
    polarity: 'negative',
    severity: 2,
    point_value: 1,
    color: '#f59e0b',
    icon: 'map-pin-off',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'verbal_warning',
    display_order: 103,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Disruption (low)',
    name_ar: 'إزعاج بسيط',
    polarity: 'negative',
    severity: 2,
    point_value: 1,
    color: '#f59e0b',
    icon: 'volume-2',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'verbal_warning',
    display_order: 104,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Missed homework',
    name_ar: 'واجب منزلي ناقص',
    polarity: 'negative',
    severity: 2,
    point_value: 1,
    color: '#f59e0b',
    icon: 'book-x',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'verbal_warning',
    display_order: 105,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Disrespect (low)',
    name_ar: 'عدم احترام بسيط',
    polarity: 'negative',
    severity: 2,
    point_value: 1,
    color: '#f59e0b',
    icon: 'alert-circle',
    requires_follow_up: false,
    requires_parent_notification: true,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'verbal_warning',
    display_order: 106,
    is_active: true,
    is_system: true,
  },

  // ─── Negative — moderate (severity 4, 3 pt) ──────────────────────────────
  {
    name: 'Disruption (sustained)',
    name_ar: 'إزعاج مستمر',
    polarity: 'negative',
    severity: 4,
    point_value: 3,
    color: '#f97316',
    icon: 'alert-octagon',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'written_warning',
    display_order: 200,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Defiance',
    name_ar: 'تحدٍّ',
    polarity: 'negative',
    severity: 4,
    point_value: 3,
    color: '#f97316',
    icon: 'x',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'written_warning',
    display_order: 201,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Bullying (verbal)',
    name_ar: 'تنمر لفظي',
    polarity: 'negative',
    severity: 4,
    point_value: 3,
    color: '#f97316',
    icon: 'message-square-x',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: true,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'written_warning',
    display_order: 202,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Lying / dishonesty',
    name_ar: 'كذب',
    polarity: 'negative',
    severity: 4,
    point_value: 3,
    color: '#f97316',
    icon: 'eye-off',
    requires_follow_up: false,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'written_warning',
    display_order: 203,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Damage to property (minor)',
    name_ar: 'إتلاف ممتلكات',
    polarity: 'negative',
    severity: 4,
    point_value: 3,
    color: '#f97316',
    icon: 'hammer',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'written_warning',
    display_order: 204,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Inappropriate language',
    name_ar: 'لغة غير لائقة',
    polarity: 'negative',
    severity: 4,
    point_value: 3,
    color: '#f97316',
    icon: 'message-circle-warning',
    requires_follow_up: false,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'written_warning',
    display_order: 205,
    is_active: true,
    is_system: true,
  },

  // ─── Negative — major (severity 7, 5 pt) ─────────────────────────────────
  {
    name: 'Bullying (physical/cyber)',
    name_ar: 'تنمر جسدي أو إلكتروني',
    polarity: 'negative',
    severity: 7,
    point_value: 5,
    color: '#dc2626',
    icon: 'shield-alert',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: true,
    converts_to_safeguarding: true,
    parent_visible: true,
    benchmark_category: 'external_suspension',
    display_order: 300,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Theft',
    name_ar: 'سرقة',
    polarity: 'negative',
    severity: 7,
    point_value: 5,
    color: '#dc2626',
    icon: 'alert-triangle',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: true,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'external_suspension',
    display_order: 301,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Fighting',
    name_ar: 'عراك',
    polarity: 'negative',
    severity: 7,
    point_value: 5,
    color: '#dc2626',
    icon: 'swords',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: true,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'external_suspension',
    display_order: 302,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Drug-related concern',
    name_ar: 'مخاوف متعلقة بالمخدرات',
    polarity: 'negative',
    severity: 7,
    point_value: 5,
    color: '#dc2626',
    icon: 'pill-bottle',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: true,
    converts_to_safeguarding: true,
    parent_visible: true,
    benchmark_category: 'external_suspension',
    display_order: 303,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Major property damage',
    name_ar: 'إتلاف كبير للممتلكات',
    polarity: 'negative',
    severity: 7,
    point_value: 5,
    color: '#dc2626',
    icon: 'alert-octagon',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: true,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'external_suspension',
    display_order: 304,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Discrimination / harassment',
    name_ar: 'تمييز أو تحرش',
    polarity: 'negative',
    severity: 7,
    point_value: 5,
    color: '#dc2626',
    icon: 'user-x',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: true,
    converts_to_safeguarding: true,
    parent_visible: true,
    benchmark_category: 'external_suspension',
    display_order: 305,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Weapons-related concern',
    name_ar: 'مخاوف متعلقة بالأسلحة',
    polarity: 'negative',
    severity: 7,
    point_value: 5,
    color: '#dc2626',
    icon: 'alert-triangle',
    requires_follow_up: true,
    requires_parent_notification: true,
    requires_parent_ack: true,
    auto_create_pastoral_concern: true,
    converts_to_safeguarding: true,
    parent_visible: true,
    benchmark_category: 'external_suspension',
    display_order: 306,
    is_active: true,
    is_system: true,
  },

  // ─── Positive — minor (severity 1, 1 pt) ─────────────────────────────────
  {
    name: 'Effort',
    name_ar: 'جهد',
    polarity: 'positive',
    severity: 1,
    point_value: 1,
    color: '#22c55e',
    icon: 'sparkles',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'minor_positive',
    display_order: 400,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Helpfulness',
    name_ar: 'تعاون',
    polarity: 'positive',
    severity: 1,
    point_value: 1,
    color: '#22c55e',
    icon: 'hand-helping',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'minor_positive',
    display_order: 401,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Punctuality',
    name_ar: 'التزام بالوقت',
    polarity: 'positive',
    severity: 1,
    point_value: 1,
    color: '#22c55e',
    icon: 'clock',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'minor_positive',
    display_order: 402,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Participation',
    name_ar: 'مشاركة',
    polarity: 'positive',
    severity: 1,
    point_value: 1,
    color: '#22c55e',
    icon: 'hand',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'minor_positive',
    display_order: 403,
    is_active: true,
    is_system: true,
  },

  // ─── Positive — moderate (severity 3, 3 pt) ──────────────────────────────
  {
    name: 'Outstanding work',
    name_ar: 'عمل متميز',
    polarity: 'positive',
    severity: 3,
    point_value: 3,
    color: '#16a34a',
    icon: 'star',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'merit',
    display_order: 500,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Leadership',
    name_ar: 'قيادة',
    polarity: 'positive',
    severity: 3,
    point_value: 3,
    color: '#16a34a',
    icon: 'crown',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'merit',
    display_order: 501,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Kindness',
    name_ar: 'لطف',
    polarity: 'positive',
    severity: 3,
    point_value: 3,
    color: '#16a34a',
    icon: 'heart',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'merit',
    display_order: 502,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Improvement',
    name_ar: 'تحسن',
    polarity: 'positive',
    severity: 3,
    point_value: 3,
    color: '#16a34a',
    icon: 'trending-up',
    requires_follow_up: false,
    requires_parent_notification: false,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'merit',
    display_order: 503,
    is_active: true,
    is_system: true,
  },

  // ─── Positive — major (severity 5, 5 pt) ─────────────────────────────────
  {
    name: 'Exceptional achievement',
    name_ar: 'إنجاز استثنائي',
    polarity: 'positive',
    severity: 5,
    point_value: 5,
    color: '#059669',
    icon: 'trophy',
    requires_follow_up: false,
    requires_parent_notification: true,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'major_positive',
    display_order: 600,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Acts of integrity',
    name_ar: 'نزاهة',
    polarity: 'positive',
    severity: 5,
    point_value: 5,
    color: '#059669',
    icon: 'shield',
    requires_follow_up: false,
    requires_parent_notification: true,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'major_positive',
    display_order: 601,
    is_active: true,
    is_system: true,
  },
  {
    name: 'Community contribution',
    name_ar: 'مساهمة مجتمعية',
    polarity: 'positive',
    severity: 5,
    point_value: 5,
    color: '#059669',
    icon: 'users',
    requires_follow_up: false,
    requires_parent_notification: true,
    requires_parent_ack: false,
    auto_create_pastoral_concern: false,
    converts_to_safeguarding: false,
    parent_visible: true,
    benchmark_category: 'major_positive',
    display_order: 602,
    is_active: true,
    is_system: true,
  },
];

/**
 * Keys of the AI modules gated by the per-module flag. Kept in sync with
 * the `module_key` values inserted by the foundation migration.
 */
export const WELLBEING_AI_MODULE_KEYS = [
  'behaviour',
  'pastoral',
  'staff_wellbeing',
  'early_warning',
] as const;

export type WellbeingAiModuleKey = (typeof WELLBEING_AI_MODULE_KEYS)[number];
