import { Injectable, Logger } from '@nestjs/common';
import ExcelJS from 'exceljs';

import type { ExportColumn, ExportColumnType, ExportInput } from '../report-export.types';

/**
 * Strip the leading `#` from a 3- or 6-digit hex colour so it can be used as
 * the `argb` value expected by exceljs. Colours without a hash (or with an
 * alpha prefix already) pass through. Invalid values fall back to a neutral
 * slate so the spreadsheet still renders.
 */
function hexToArgb(hex: string, fallback = '00334155'): string {
  const cleaned = hex.startsWith('#') ? hex.slice(1) : hex;
  if (/^[0-9a-fA-F]{6}$/.test(cleaned)) return `FF${cleaned.toUpperCase()}`;
  if (/^[0-9a-fA-F]{8}$/.test(cleaned)) return cleaned.toUpperCase();
  if (/^[0-9a-fA-F]{3}$/.test(cleaned)) {
    const [r, g, b] = cleaned.split('');
    return `FF${r}${r}${g}${g}${b}${b}`.toUpperCase();
  }
  return fallback;
}

function excelNumberFormatForColumn(
  type: ExportColumnType,
  currencyCode: string,
): string | undefined {
  switch (type) {
    case 'date':
      return 'dd/mm/yyyy';
    case 'currency': {
      // Escape the currency code into the format string. If the code has
      // characters that Excel format strings choke on, fall back to a plain
      // decimal format prefixed with the code.
      const safe = currencyCode.replace(/"/g, '');
      return `"${safe}" #,##0.00`;
    }
    case 'number':
      return '#,##0.##';
    default:
      return undefined;
  }
}

function excelValueForColumn(
  value: unknown,
  type: ExportColumnType,
): string | number | Date | boolean | null {
  if (value === null || value === undefined) return null;

  switch (type) {
    case 'date': {
      if (value instanceof Date) return value;
      const d = new Date(String(value));
      return Number.isNaN(d.getTime()) ? String(value) : d;
    }
    case 'number':
    case 'currency': {
      if (typeof value === 'number') return value;
      const n = Number(value);
      return Number.isNaN(n) ? String(value) : n;
    }
    case 'boolean':
      return value ? 'TRUE' : 'FALSE';
    case 'string':
    default:
      return String(value);
  }
}

/**
 * exceljs-backed Excel renderer. Produces a two-sheet workbook:
 *
 *  - **Info** — human-readable metadata (name / description / generated-at /
 *    generated-by / filters summary) with the primary brand colour applied to
 *    the title.
 *  - **Data** — one row per export row, with column-type-aware formatting,
 *    frozen header row, autofilter, and striped body rows.
 */
@Injectable()
export class ExcelRenderer {
  private readonly logger = new Logger(ExcelRenderer.name);

  async render(input: ExportInput): Promise<Buffer> {
    const { report, data, branding } = input;
    const workbook = new ExcelJS.Workbook();
    workbook.creator = report.generated_by;
    workbook.created = report.generated_at;
    workbook.modified = report.generated_at;

    const primaryArgb = hexToArgb(branding.primary_color);

    // ─── Info sheet ────────────────────────────────────────────────────────
    const info = workbook.addWorksheet('Info');
    info.views = [{ showGridLines: false, rightToLeft: branding.locale === 'ar' }];
    info.columns = [{ width: 24 }, { width: 72 }];

    const titleRow = info.addRow([report.name]);
    titleRow.font = { bold: true, size: 16, color: { argb: primaryArgb } };
    info.mergeCells(`A${titleRow.number}:B${titleRow.number}`);
    titleRow.height = 28;

    info.addRow(['School', branding.school_name]);
    info.addRow(['Description', report.description ?? '—']);
    info.addRow(['Generated at', report.generated_at]);
    info.addRow(['Generated by', report.generated_by]);
    info.addRow(['Filters applied', report.filters_summary || '—']);

    // Format the Generated-at cell as a date.
    const generatedRow = info.lastRow && info.lastRow.number - 2;
    if (generatedRow) {
      const cell = info.getCell(generatedRow, 2);
      cell.numFmt = 'dd/mm/yyyy hh:mm';
    }

    // Apply label styling.
    for (let r = 2; r <= info.lastRow!.number; r++) {
      const labelCell = info.getCell(r, 1);
      labelCell.font = { bold: true, color: { argb: '00475569' } };
      labelCell.alignment = {
        vertical: 'top',
        horizontal: branding.locale === 'ar' ? 'right' : 'left',
      };
      const valueCell = info.getCell(r, 2);
      valueCell.alignment = {
        vertical: 'top',
        horizontal: branding.locale === 'ar' ? 'right' : 'left',
        wrapText: true,
      };
    }

    // ─── Data sheet ────────────────────────────────────────────────────────
    const dataSheet = workbook.addWorksheet('Data');
    dataSheet.views = [
      {
        state: 'frozen',
        ySplit: 1,
        rightToLeft: branding.locale === 'ar',
      },
    ];

    this.writeDataSheet(dataSheet, data.columns, data.rows, branding.currency_code, primaryArgb);

    try {
      const raw = await workbook.xlsx.writeBuffer();
      return Buffer.from(raw as ArrayBuffer);
    } catch (err) {
      this.logger.error(
        `Excel render failed for tenant=${input.tenantId} report="${input.report.name}": ${(err as Error).message}`,
      );
      throw err;
    }
  }

  private writeDataSheet(
    sheet: ExcelJS.Worksheet,
    columns: ExportColumn[],
    rows: Record<string, unknown>[],
    currencyCode: string,
    primaryArgb: string,
  ): void {
    sheet.columns = columns.map((col) => ({
      header: col.label,
      key: col.id,
      width: Math.min(Math.max(col.label.length + 2, 12), 32),
    }));

    const headerRow = sheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: primaryArgb } };
    headerRow.alignment = { vertical: 'middle' };
    headerRow.height = 22;
    headerRow.eachCell((cell) => {
      cell.border = { bottom: { style: 'medium', color: { argb: primaryArgb } } };
    });

    for (const row of rows) {
      const values: Record<string, string | number | boolean | Date | null> = {};
      for (const col of columns) {
        values[col.id] = excelValueForColumn(row[col.id], col.type);
      }
      const added = sheet.addRow(values);
      added.eachCell((cell, colNumber) => {
        const col = columns[colNumber - 1];
        if (!col) return;
        const numFmt = excelNumberFormatForColumn(col.type, currencyCode);
        if (numFmt) cell.numFmt = numFmt;
        if (col.type === 'number' || col.type === 'currency') {
          cell.alignment = { horizontal: 'right' };
        } else if (col.type === 'boolean') {
          cell.alignment = { horizontal: 'center' };
        }
      });

      // Subtle striping on even body rows.
      if (added.number % 2 === 0) {
        added.eachCell((cell) => {
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: '00F8FAFC' },
          };
        });
      }
    }

    if (columns.length > 0) {
      sheet.autoFilter = {
        from: { row: 1, column: 1 },
        to: { row: Math.max(1, rows.length + 1), column: columns.length },
      };
    }
  }
}
