import ExcelJS from 'exceljs';

import type { ExportInput } from '../report-export.types';

import { ExcelRenderer } from './excel-renderer';

const TENANT_ID = '11111111-1111-1111-1111-111111111111';

function makeInput(overrides: Partial<ExportInput['data']> = {}): ExportInput {
  return {
    tenantId: TENANT_ID,
    report: {
      name: 'Sample Student Export',
      description: 'Demographic snapshot',
      filters_summary: 'Year 10 · this term',
      generated_by: 'owner@nhqs.test',
      generated_at: new Date('2026-04-24T09:00:00Z'),
    },
    data: {
      columns: [
        { id: 'student', label: 'Student', type: 'string' },
        { id: 'rate', label: 'Attendance', type: 'number' },
        { id: 'paid', label: 'Fees paid', type: 'currency' },
        { id: 'last_seen', label: 'Last seen', type: 'date' },
        { id: 'at_risk', label: 'At risk', type: 'boolean' },
      ],
      rows: [
        {
          student: 'Alice Andrews',
          rate: 0.94,
          paid: 1200.5,
          last_seen: new Date('2026-04-22T00:00:00Z'),
          at_risk: false,
        },
        {
          student: 'Bashir Bokova',
          rate: 0.82,
          paid: 0,
          last_seen: '2026-04-23',
          at_risk: true,
        },
      ],
      ...overrides,
    },
    branding: {
      tenant_id: TENANT_ID,
      school_name: 'NHQS Academy',
      logo_url: null,
      primary_color: '#1d4ed8',
      secondary_color: '#64748b',
      locale: 'en',
      currency_code: 'EUR',
    },
  };
}

describe('ExcelRenderer', () => {
  const renderer = new ExcelRenderer();

  it('produces a valid xlsx (ZIP) buffer over 1 KB', async () => {
    const buffer = await renderer.render(makeInput());
    expect(buffer).toBeInstanceOf(Buffer);
    expect(buffer.length).toBeGreaterThan(1024);
    // xlsx is a zip file — first two bytes are "PK".
    expect(Buffer.from(buffer.subarray(0, 2)).toString('ascii')).toBe('PK');
  });

  it('writes an Info sheet with metadata and a Data sheet with rows + autofilter', async () => {
    const buffer = await renderer.render(makeInput());

    const wb = new ExcelJS.Workbook();
    await wb.xlsx.load(
      buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength) as ArrayBuffer,
    );

    const info = wb.getWorksheet('Info');
    const data = wb.getWorksheet('Data');
    expect(info).toBeDefined();
    expect(data).toBeDefined();

    // Info sheet: title row + six metadata rows (school / description /
    // generated at / generated by / filters) = 6 rows minimum.
    expect(info!.rowCount).toBeGreaterThanOrEqual(6);
    expect(info!.getCell('A1').value).toBe('Sample Student Export');

    // Data sheet: 1 header row + 2 data rows.
    expect(data!.rowCount).toBe(3);
    expect(data!.getRow(1).getCell(1).value).toBe('Student');
    // exceljs normalises the autoFilter object into an A1-style range string
    // when reading a workbook back out, so assert on the stringified form.
    expect(data!.autoFilter).toBe('A1:E3');
  });

  it('flips rightToLeft view when the tenant locale is Arabic', async () => {
    const buffer = await renderer.render({
      ...makeInput(),
      branding: {
        tenant_id: TENANT_ID,
        school_name: 'المدرسة',
        logo_url: null,
        primary_color: '#1d4ed8',
        secondary_color: '#64748b',
        locale: 'ar',
        currency_code: 'AED',
      },
    });
    const wb = new ExcelJS.Workbook();
    await wb.xlsx.load(
      buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength) as ArrayBuffer,
    );
    const dataSheet = wb.getWorksheet('Data');
    expect(dataSheet!.views?.[0]?.rightToLeft).toBe(true);
  });

  it('renders column-type-aware number formats', async () => {
    const buffer = await renderer.render(makeInput());
    const wb = new ExcelJS.Workbook();
    await wb.xlsx.load(
      buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength) as ArrayBuffer,
    );
    const data = wb.getWorksheet('Data')!;
    // Row 2 is the first body row; column 3 is the currency column.
    expect(data.getRow(2).getCell(3).numFmt).toContain('EUR');
    // Column 4 is the date column.
    expect(data.getRow(2).getCell(4).numFmt).toBe('dd/mm/yyyy');
  });
});
