/**
 * System role definitions and their default permission assignments.
 * System roles are created per-tenant (with tenant_id) and are immutable.
 */

export interface SystemRoleSeed {
  role_key: string;
  display_name: string;
  role_tier: 'platform' | 'admin' | 'staff' | 'parent';
  default_permissions: string[];
}

export const SYSTEM_ROLES: SystemRoleSeed[] = [
  {
    role_key: 'platform_owner',
    display_name: 'Platform Owner',
    role_tier: 'platform',
    default_permissions: [
      'tenants.manage',
      'tenants.view',
      'platform.impersonate',
      'platform.reset_mfa',
    ],
  },
  {
    role_key: 'school_owner',
    display_name: 'School Owner',
    role_tier: 'platform',
    default_permissions: [
      // Platform
      'tenants.manage',
      'tenants.view',
      'platform.reset_mfa',
      // Users (full access — School Owner account is protected from suspension by a guard)
      'users.manage',
      'users.view',
      'users.invite',
      // Settings & Config
      'settings.manage',
      'branding.manage',
      'stripe.manage',
      'notifications.manage',
      'modules.manage',
      'domains.manage',
      'roles.manage',
      // Approvals
      'approvals.manage',
      'approvals.view',
      // Payroll (full access including bank details for executing transfers)
      'payroll.view',
      'payroll.manage_compensation',
      'payroll.create_run',
      'payroll.finalise_run',
      'payroll.generate_payslips',
      'payroll.view_bank_details',
      'payroll.view_reports',
      // Schedule
      'schedule.manage',
      'schedule.override_conflict',
      'schedule.manage_closures',
      'schedule.configure_period_grid',
      'schedule.configure_requirements',
      'schedule.configure_availability',
      'schedule.manage_preferences',
      'schedule.run_auto',
      'schedule.apply_auto',
      'schedule.pin_entries',
      'schedule.view_auto_reports',
      'schedule.view_own',
      'schedule.manage_own_preferences',
      'schedule.view_own_satisfaction',
      // Leave & Cover
      'schedule.manage_substitutions',
      'leave.approve_requests',
      'leave.manage_types',
      // Search
      'search.view',
      // Students & Attendance
      'students.manage',
      'students.view',
      'attendance.manage',
      'attendance.view',
      'attendance.take',
      'attendance.take_any_class',
      'attendance.amend_historical',
      'attendance.override_closure',
      'attendance.view_pattern_reports',
      // Gradebook
      'gradebook.manage',
      'gradebook.view',
      'gradebook.enter_grades',
      'gradebook.override_final_grade',
      'gradebook.publish_report_cards',
      'report_cards.view',
      'report_cards.comment',
      'report_cards.manage',
      'transcripts.generate',
      // Admissions & Finance
      'admissions.manage',
      'admissions.view',
      'finance.manage',
      'finance.view',
      'finance.process_payments',
      'finance.issue_refunds',
      // Communications, Inquiries, Website, Analytics, Compliance
      'communications.manage',
      'communications.view',
      'communications.send',
      'inquiries.view',
      'inquiries.respond',
      'website.manage',
      'analytics.view',
      'curriculum_matrix.manage',
      'compliance.manage',
      'compliance.view',
      // SEN
      'sen.view',
      'sen.manage',
      'sen.manage_resources',
      'sen.view_sensitive',
      'sen.admin',
      'legal.view',
      'legal.manage',
      'privacy.view',
      'privacy.manage',
      'consent.manage',
      'consent.view',
      // Parent capabilities
      'parent.view_own_students',
      'parent.view_attendance',
      'parent.view_grades',
      'parent.view_invoices',
      'parent.make_payments',
      'parent.submit_inquiry',
      'parent.view_announcements',
      'parent.view_transcripts',
      // Inbox — School Owner gets all five keys
      'inbox.settings.read',
      'inbox.settings.write',
      'inbox.send',
      'inbox.oversight.read',
      'inbox.oversight.write',
      // Wellbeing rebuild (Impl 01) — super-hub, AI flags, channel prefs,
      // dedicated safeguarding sub-hub
      'wellbeing.view_dashboard',
      'wellbeing_notifications.configure',
      'ai_flag.manage',
      'safeguarding.dedicated_view',
      // Behaviour — owner can log incidents (S3 walkthrough — W-S3-014)
      'behaviour.log',
      // Early warning (S6 walkthrough — W-S6-001): owner has full configuration + assignment rights
      'early_warning.view',
      'early_warning.manage',
      'early_warning.acknowledge',
      'early_warning.assign',
      // Excluded: platform.impersonate (reserved for future platform super-admin role)
    ],
  },
  {
    role_key: 'school_principal',
    display_name: 'School Principal',
    role_tier: 'admin',
    default_permissions: [
      // Search
      'search.view',
      // Users & Roles
      'users.manage',
      'users.invite',
      'users.view',
      'roles.manage',
      // Settings & Config
      'settings.manage',
      'branding.manage',
      'stripe.manage',
      'notifications.manage',
      'modules.manage',
      'domains.manage',
      // Approvals
      'approvals.manage',
      'approvals.view',
      // Payroll (full access)
      'payroll.view',
      'payroll.manage_compensation',
      'payroll.create_run',
      'payroll.finalise_run',
      'payroll.generate_payslips',
      'payroll.view_bank_details',
      'payroll.view_reports',
      // Schedule (full admin)
      'schedule.manage',
      'schedule.override_conflict',
      'schedule.manage_closures',
      'schedule.configure_period_grid',
      'schedule.configure_requirements',
      'schedule.configure_availability',
      'schedule.manage_preferences',
      'schedule.run_auto',
      'schedule.apply_auto',
      'schedule.pin_entries',
      'schedule.view_auto_reports',
      // Schedule enhanced
      'schedule.manage_substitutions',
      'schedule.view_reports',
      'schedule.manage_exams',
      'schedule.manage_scenarios',
      'leave.approve_requests',
      'leave.manage_types',
      // Students, Attendance, Gradebook
      'students.manage',
      'students.view',
      'attendance.manage',
      'attendance.view',
      'attendance.take',
      'attendance.take_any_class',
      'attendance.view_pattern_reports',
      'gradebook.manage',
      'gradebook.view',
      'gradebook.enter_grades',
      'gradebook.override_final_grade',
      'gradebook.publish_report_cards',
      'gradebook.apply_curve',
      'gradebook.view_analytics',
      'gradebook.publish_grades_to_parents',
      'gradebook.manage_ai_grading',
      'gradebook.approve_ai_grading',
      'report_cards.approve',
      'report_cards.manage_templates',
      'report_cards.bulk_operations',
      'report_cards.view',
      'report_cards.comment',
      'report_cards.manage',
      'transcripts.generate',
      // Admissions, Finance
      'admissions.manage',
      'admissions.view',
      'finance.manage',
      'finance.view',
      'finance.process_payments',
      'finance.issue_refunds',
      // Communications, Inquiries, Website, Analytics, Compliance
      'communications.manage',
      'communications.view',
      'communications.send',
      'inquiries.view',
      'inquiries.respond',
      'website.manage',
      'analytics.view',
      'curriculum_matrix.manage',
      'compliance.manage',
      'compliance.view',
      // SEN
      'sen.view',
      'sen.manage',
      'sen.manage_resources',
      'sen.view_sensitive',
      'sen.admin',
      'legal.view',
      'legal.manage',
      'privacy.view',
      'privacy.manage',
      'consent.manage',
      'consent.view',
      // Inbox — Principal gets all five keys
      'inbox.settings.read',
      'inbox.settings.write',
      'inbox.send',
      'inbox.oversight.read',
      'inbox.oversight.write',
      // Safeguarding — principal is the Designated Safeguarding Lead
      'safeguarding.view',
      'safeguarding.manage',
      'safeguarding.report',
      'safeguarding.seal',
      'safeguarding.dedicated_view',
      // Wellbeing rebuild (Impl 01)
      'wellbeing.view_dashboard',
      'wellbeing_notifications.configure',
      'ai_flag.manage',
      // Behaviour — principal can log + oversee (S3 walkthrough — W-S3-014)
      'behaviour.log',
      // Early warning (S6 walkthrough — W-S6-001): principal has full configuration + assignment rights (DSL + pastoral oversight)
      'early_warning.view',
      'early_warning.manage',
      'early_warning.acknowledge',
      'early_warning.assign',
    ],
  },
  {
    role_key: 'admin',
    display_name: 'Admin',
    role_tier: 'admin',
    default_permissions: [
      'search.view',
      'users.manage',
      'users.invite',
      'users.view',
      'roles.manage',
      'settings.manage',
      'branding.manage',
      'notifications.manage',
      'approvals.view',
      // Schedule (admin without auto-run/apply)
      'schedule.manage',
      'schedule.manage_closures',
      'schedule.configure_period_grid',
      'schedule.configure_requirements',
      'schedule.configure_availability',
      'schedule.manage_preferences',
      'schedule.pin_entries',
      'schedule.view_auto_reports',
      // Schedule enhanced
      'schedule.manage_substitutions',
      'schedule.view_reports',
      'schedule.manage_exams',
      'schedule.manage_scenarios',
      'leave.approve_requests',
      'leave.manage_types',
      // Students, Attendance, Gradebook
      'students.manage',
      'students.view',
      'attendance.manage',
      'attendance.view',
      'attendance.take',
      'attendance.take_any_class',
      'attendance.view_pattern_reports',
      'gradebook.manage',
      'gradebook.view',
      'gradebook.enter_grades',
      'gradebook.override_final_grade',
      'gradebook.publish_report_cards',
      'gradebook.apply_curve',
      'gradebook.view_analytics',
      'gradebook.publish_grades_to_parents',
      'gradebook.manage_ai_grading',
      'gradebook.approve_ai_grading',
      'report_cards.approve',
      'report_cards.manage_templates',
      'report_cards.bulk_operations',
      'report_cards.view',
      'report_cards.comment',
      'report_cards.manage',
      'transcripts.generate',
      // Admissions
      'admissions.manage',
      'admissions.view',
      // Finance (view only by default)
      'finance.view',
      // Communications, Inquiries
      'communications.manage',
      'communications.view',
      'communications.send',
      'inquiries.view',
      'inquiries.respond',
      // Website, Analytics, Compliance
      'website.manage',
      'analytics.view',
      // SEN
      'sen.view',
      'sen.manage',
      'sen.manage_resources',
      'sen.view_sensitive',
      'sen.admin',
      'compliance.view',
      'legal.view',
      'legal.manage',
      'privacy.view',
      'privacy.manage',
      'consent.manage',
      'consent.view',
      // Inbox — office-style admin staff get send only
      'inbox.send',
      // Wellbeing rebuild (Impl 01) — staff-visible dashboard
      'wellbeing.view_dashboard',
      // Early warning (S6 walkthrough — W-S6-001): admins need view + acknowledge + assign; configuration is principal-only
      'early_warning.view',
      'early_warning.acknowledge',
      'early_warning.assign',
    ],
  },
  {
    role_key: 'teacher',
    display_name: 'Teacher',
    role_tier: 'staff',
    default_permissions: [
      'students.view',
      'attendance.take',
      'attendance.view',
      'gradebook.enter_grades',
      'gradebook.view',
      'gradebook.manage_ai_grading',
      'report_cards.view',
      'report_cards.comment',
      'schedule.view_own',
      'schedule.view_class',
      'schedule.manage_own_preferences',
      'schedule.view_own_satisfaction',
      'schedule.view_personal_timetable',
      // Leave & Cover — teacher self-serve
      'schedule.report_own_absence',
      'schedule.respond_to_offer',
      'leave.submit_request',
      'sen.view',
      'legal.view',
      // Homework — teachers assign, mark, view analytics
      'homework.view',
      'homework.manage',
      'homework.mark_own',
      'homework.view_diary',
      'homework.write_diary',
      'homework.view_analytics',
      // Inbox — teachers can send (policy engine gates actual audience)
      'inbox.send',
      // Wellbeing rebuild (Impl 01) — staff-visible dashboard
      'wellbeing.view_dashboard',
      // Behaviour — teachers can log incidents/recognition (S3 walkthrough — W-S3-014)
      'behaviour.log',
      // Early warning (S6 walkthrough — W-S6-001): teachers see their own class's risk list and acknowledge
      'early_warning.view',
      'early_warning.acknowledge',
    ],
  },
  {
    role_key: 'attendance_officer',
    display_name: 'Attendance Officer',
    role_tier: 'staff',
    default_permissions: [
      'students.view',
      'attendance.view',
      'attendance.take',
      'attendance.take_any_class',
      'schedule.view_class',
      // Wellbeing rebuild (Impl 01) — staff-visible dashboard
      'wellbeing.view_dashboard',
    ],
  },
  {
    role_key: 'accounting',
    display_name: 'Accounting',
    role_tier: 'admin',
    default_permissions: [
      'finance.manage',
      'finance.view',
      'finance.process_payments',
      'legal.view',
      // Inbox — finance staff can send
      'inbox.send',
      // Wellbeing rebuild (Impl 01) — staff-visible dashboard
      'wellbeing.view_dashboard',
    ],
  },
  {
    role_key: 'front_office',
    display_name: 'Front Office',
    role_tier: 'admin',
    default_permissions: [
      'admissions.manage',
      'admissions.view',
      'report_cards.view',
      'legal.view',
      // Inbox — front office can send
      'inbox.send',
      // Wellbeing rebuild (Impl 01) — staff-visible dashboard
      'wellbeing.view_dashboard',
    ],
  },
  {
    role_key: 'parent',
    display_name: 'Parent',
    role_tier: 'parent',
    default_permissions: [
      'parent.view_own_students',
      'parent.view_attendance',
      'parent.view_behaviour',
      'parent.view_grades',
      'parent.view_invoices',
      'parent.make_payments',
      'parent.submit_inquiry',
      'parent.view_announcements',
      'parent.view_transcripts',
      'behaviour.appeal',
      'schedule.view_class',
      'legal.view',
      // Inbox — parents hold the send bit; the policy engine decides whether
      // they may actually start a thread or only reply on allow_replies threads.
      'inbox.send',
    ],
  },
  {
    role_key: 'school_vice_principal',
    display_name: 'School Vice-Principal',
    role_tier: 'admin',
    default_permissions: [
      'admissions.manage',
      'admissions.view',
      'legal.view',
      'legal.manage',
      'privacy.view',
      'privacy.manage',
      'report_cards.view',
      'report_cards.comment',
      'report_cards.manage',
      // Leave & Cover — vice principals approve leave + manage substitutions
      'schedule.manage_substitutions',
      'leave.approve_requests',
      // Inbox — Vice Principal gets all five keys (admin tier)
      'inbox.settings.read',
      'inbox.settings.write',
      'inbox.send',
      'inbox.oversight.read',
      'inbox.oversight.write',
      // Safeguarding — VP can read + mutate concerns but not seal (dual-control
      // is reserved for principal + owner)
      'safeguarding.view',
      'safeguarding.manage',
      'safeguarding.report',
      'safeguarding.dedicated_view',
      // Wellbeing rebuild (Impl 01) — super-hub + dedicated safeguarding view
      'wellbeing.view_dashboard',
      // Behaviour — VP can log incidents (S3 walkthrough — W-S3-014)
      'behaviour.log',
      // Early warning (S6 walkthrough — W-S6-001): VP has view + acknowledge + assign (configuration reserved to principal/owner)
      'early_warning.view',
      'early_warning.acknowledge',
      'early_warning.assign',
    ],
  },
  {
    role_key: 'student',
    display_name: 'Student',
    role_tier: 'parent',
    default_permissions: [
      'legal.view',
      'schedule.view_class',
      // SCHED-032 — students view their own timetable through the parent-tier
      // endpoint `GET /v1/parent/timetable/self`, which reuses the rich-shape
      // assembler from the scheduling module. See ParentTimetableService.
      'parent.view_timetable',
      // Inbox — students hold the send bit; the policy engine decides whether
      // they may actually start or reply (default: reply-only on allow_replies).
      'inbox.send',
      // Wave 3 homework — view own assignments + submit work.
      'homework.submit.own',
    ],
  },
];
