/**
 * System role definitions and their default permission assignments.
 * System roles are created per-tenant (with tenant_id) and are immutable.
 */

export interface SystemRoleSeed {
  role_key: string;
  display_name: string;
  role_tier: 'platform' | 'admin' | 'staff' | 'parent';
  default_permissions: string[];
}

export const SYSTEM_ROLES: SystemRoleSeed[] = [
  {
    role_key: 'platform_owner',
    display_name: 'Platform Owner',
    role_tier: 'platform',
    default_permissions: [
      'tenants.manage',
      'tenants.view',
      'platform.impersonate',
      'platform.reset_mfa',
    ],
  },
  {
    role_key: 'school_owner',
    display_name: 'School Owner',
    role_tier: 'platform',
    default_permissions: [
      // Platform
      'tenants.manage',
      'tenants.view',
      'platform.reset_mfa',
      // Users (full access — School Owner account is protected from suspension by a guard)
      'users.manage',
      'users.view',
      'users.invite',
      // Settings & Config
      'settings.manage',
      'branding.manage',
      'stripe.manage',
      'notifications.manage',
      'modules.manage',
      'domains.manage',
      'roles.manage',
      // Approvals
      'approvals.manage',
      'approvals.view',
      // Payroll (full access including bank details for executing transfers)
      'payroll.view',
      'payroll.manage_compensation',
      'payroll.create_run',
      'payroll.finalise_run',
      'payroll.generate_payslips',
      'payroll.view_bank_details',
      'payroll.view_reports',
      // Schedule
      'schedule.manage',
      'schedule.override_conflict',
      'schedule.manage_closures',
      'schedule.configure_period_grid',
      'schedule.configure_requirements',
      'schedule.configure_availability',
      'schedule.manage_preferences',
      'schedule.run_auto',
      'schedule.apply_auto',
      'schedule.pin_entries',
      'schedule.view_auto_reports',
      'schedule.view_own',
      'schedule.manage_own_preferences',
      'schedule.view_own_satisfaction',
      // Search
      'search.view',
      // Students & Attendance
      'students.manage',
      'students.view',
      'attendance.manage',
      'attendance.view',
      'attendance.take',
      'attendance.amend_historical',
      'attendance.override_closure',
      // Gradebook
      'gradebook.manage',
      'gradebook.view',
      'gradebook.enter_grades',
      'gradebook.override_final_grade',
      'gradebook.publish_report_cards',
      'report_cards.view',
      'report_cards.comment',
      'report_cards.manage',
      'transcripts.generate',
      // Admissions & Finance
      'admissions.manage',
      'admissions.view',
      'finance.manage',
      'finance.view',
      'finance.process_payments',
      'finance.issue_refunds',
      // Communications, Inquiries, Website, Analytics, Compliance
      'communications.manage',
      'communications.view',
      'communications.send',
      'inquiries.view',
      'inquiries.respond',
      'website.manage',
      'analytics.view',
      'curriculum_matrix.manage',
      'compliance.manage',
      'compliance.view',
      // SEN
      'sen.view',
      'sen.manage',
      'sen.manage_resources',
      'sen.view_sensitive',
      'sen.admin',
      'legal.view',
      'legal.manage',
      'privacy.view',
      'privacy.manage',
      'consent.manage',
      'consent.view',
      // Parent capabilities
      'parent.view_own_students',
      'parent.view_attendance',
      'parent.view_grades',
      'parent.view_invoices',
      'parent.make_payments',
      'parent.submit_inquiry',
      'parent.view_announcements',
      'parent.view_transcripts',
      // Inbox — School Owner gets all five keys
      'inbox.settings.read',
      'inbox.settings.write',
      'inbox.send',
      'inbox.oversight.read',
      'inbox.oversight.write',
      // Excluded: platform.impersonate (reserved for future platform super-admin role)
    ],
  },
  {
    role_key: 'school_principal',
    display_name: 'School Principal',
    role_tier: 'admin',
    default_permissions: [
      // Search
      'search.view',
      // Users & Roles
      'users.manage',
      'users.invite',
      'users.view',
      'roles.manage',
      // Settings & Config
      'settings.manage',
      'branding.manage',
      'stripe.manage',
      'notifications.manage',
      'modules.manage',
      'domains.manage',
      // Approvals
      'approvals.manage',
      'approvals.view',
      // Payroll (full access)
      'payroll.view',
      'payroll.manage_compensation',
      'payroll.create_run',
      'payroll.finalise_run',
      'payroll.generate_payslips',
      'payroll.view_bank_details',
      'payroll.view_reports',
      // Schedule (full admin)
      'schedule.manage',
      'schedule.override_conflict',
      'schedule.manage_closures',
      'schedule.configure_period_grid',
      'schedule.configure_requirements',
      'schedule.configure_availability',
      'schedule.manage_preferences',
      'schedule.run_auto',
      'schedule.apply_auto',
      'schedule.pin_entries',
      'schedule.view_auto_reports',
      // Schedule enhanced
      'schedule.manage_substitutions',
      'schedule.view_reports',
      'schedule.manage_exams',
      'schedule.manage_scenarios',
      // Students, Attendance, Gradebook
      'students.manage',
      'students.view',
      'attendance.manage',
      'attendance.view',
      'attendance.take',
      'gradebook.manage',
      'gradebook.view',
      'gradebook.enter_grades',
      'gradebook.override_final_grade',
      'gradebook.publish_report_cards',
      'gradebook.apply_curve',
      'gradebook.view_analytics',
      'gradebook.publish_grades_to_parents',
      'gradebook.manage_ai_grading',
      'gradebook.approve_ai_grading',
      'report_cards.approve',
      'report_cards.manage_templates',
      'report_cards.bulk_operations',
      'report_cards.view',
      'report_cards.comment',
      'report_cards.manage',
      'transcripts.generate',
      // Admissions, Finance
      'admissions.manage',
      'admissions.view',
      'finance.manage',
      'finance.view',
      'finance.process_payments',
      'finance.issue_refunds',
      // Communications, Inquiries, Website, Analytics, Compliance
      'communications.manage',
      'communications.view',
      'communications.send',
      'inquiries.view',
      'inquiries.respond',
      'website.manage',
      'analytics.view',
      'curriculum_matrix.manage',
      'compliance.manage',
      'compliance.view',
      // SEN
      'sen.view',
      'sen.manage',
      'sen.manage_resources',
      'sen.view_sensitive',
      'sen.admin',
      'legal.view',
      'legal.manage',
      'privacy.view',
      'privacy.manage',
      'consent.manage',
      'consent.view',
      // Inbox — Principal gets all five keys
      'inbox.settings.read',
      'inbox.settings.write',
      'inbox.send',
      'inbox.oversight.read',
      'inbox.oversight.write',
    ],
  },
  {
    role_key: 'admin',
    display_name: 'Admin',
    role_tier: 'admin',
    default_permissions: [
      'search.view',
      'users.manage',
      'users.invite',
      'users.view',
      'roles.manage',
      'settings.manage',
      'branding.manage',
      'notifications.manage',
      'approvals.view',
      // Schedule (admin without auto-run/apply)
      'schedule.manage',
      'schedule.manage_closures',
      'schedule.configure_period_grid',
      'schedule.configure_requirements',
      'schedule.configure_availability',
      'schedule.manage_preferences',
      'schedule.pin_entries',
      'schedule.view_auto_reports',
      // Schedule enhanced
      'schedule.manage_substitutions',
      'schedule.view_reports',
      'schedule.manage_exams',
      'schedule.manage_scenarios',
      // Students, Attendance, Gradebook
      'students.manage',
      'students.view',
      'attendance.manage',
      'attendance.view',
      'attendance.take',
      'gradebook.manage',
      'gradebook.view',
      'gradebook.enter_grades',
      'gradebook.override_final_grade',
      'gradebook.publish_report_cards',
      'gradebook.apply_curve',
      'gradebook.view_analytics',
      'gradebook.publish_grades_to_parents',
      'gradebook.manage_ai_grading',
      'gradebook.approve_ai_grading',
      'report_cards.approve',
      'report_cards.manage_templates',
      'report_cards.bulk_operations',
      'report_cards.view',
      'report_cards.comment',
      'report_cards.manage',
      'transcripts.generate',
      // Admissions
      'admissions.manage',
      'admissions.view',
      // Finance (view only by default)
      'finance.view',
      // Communications, Inquiries
      'communications.manage',
      'communications.view',
      'communications.send',
      'inquiries.view',
      'inquiries.respond',
      // Website, Analytics, Compliance
      'website.manage',
      'analytics.view',
      // SEN
      'sen.view',
      'sen.manage',
      'sen.manage_resources',
      'sen.view_sensitive',
      'sen.admin',
      'compliance.view',
      'legal.view',
      'legal.manage',
      'privacy.view',
      'privacy.manage',
      'consent.manage',
      'consent.view',
      // Inbox — office-style admin staff get send only
      'inbox.send',
    ],
  },
  {
    role_key: 'teacher',
    display_name: 'Teacher',
    role_tier: 'staff',
    default_permissions: [
      'students.view',
      'attendance.take',
      'attendance.view',
      'gradebook.enter_grades',
      'gradebook.view',
      'gradebook.manage_ai_grading',
      'report_cards.view',
      'report_cards.comment',
      'schedule.view_own',
      'schedule.manage_own_preferences',
      'schedule.view_own_satisfaction',
      'schedule.view_personal_timetable',
      'sen.view',
      'legal.view',
      // Inbox — teachers can send (policy engine gates actual audience)
      'inbox.send',
    ],
  },
  {
    role_key: 'accounting',
    display_name: 'Accounting',
    role_tier: 'admin',
    default_permissions: [
      'finance.manage',
      'finance.view',
      'finance.process_payments',
      'legal.view',
      // Inbox — finance staff can send
      'inbox.send',
    ],
  },
  {
    role_key: 'front_office',
    display_name: 'Front Office',
    role_tier: 'admin',
    default_permissions: [
      'admissions.manage',
      'admissions.view',
      'report_cards.view',
      'legal.view',
      // Inbox — front office can send
      'inbox.send',
    ],
  },
  {
    role_key: 'parent',
    display_name: 'Parent',
    role_tier: 'parent',
    default_permissions: [
      'parent.view_own_students',
      'parent.view_attendance',
      'parent.view_grades',
      'parent.view_invoices',
      'parent.make_payments',
      'parent.submit_inquiry',
      'parent.view_announcements',
      'parent.view_transcripts',
      'legal.view',
      // Inbox — parents hold the send bit; the policy engine decides whether
      // they may actually start a thread or only reply on allow_replies threads.
      'inbox.send',
    ],
  },
  {
    role_key: 'school_vice_principal',
    display_name: 'School Vice-Principal',
    role_tier: 'admin',
    default_permissions: [
      'admissions.manage',
      'admissions.view',
      'legal.view',
      'legal.manage',
      'privacy.view',
      'privacy.manage',
      'report_cards.view',
      'report_cards.comment',
      'report_cards.manage',
      // Inbox — Vice Principal gets all five keys (admin tier)
      'inbox.settings.read',
      'inbox.settings.write',
      'inbox.send',
      'inbox.oversight.read',
      'inbox.oversight.write',
    ],
  },
  {
    role_key: 'student',
    display_name: 'Student',
    role_tier: 'parent',
    default_permissions: [
      'legal.view',
      // Inbox — students hold the send bit; the policy engine decides whether
      // they may actually start or reply (default: reply-only on allow_replies).
      'inbox.send',
    ],
  },
];
