'use client';

import { useTranslations } from 'next-intl';

import { ReportCardsSettings } from './settings-types';
import { BooleanRow, NumberRow, SectionCard, SelectRow, SubSectionCard } from './settings-ui';

interface ReportCardsSectionProps {
  settings: ReportCardsSettings;
  onChange: (updates: Partial<ReportCardsSettings>) => void;
}

export function ReportCardsSection({ settings, onChange }: ReportCardsSectionProps) {
  const t = useTranslations('settings');

  return (
    <SectionCard title={t('sectionReportCards')} description={t('sectionReportCardsDesc')}>
      <SelectRow
        label={t('rcApprovalConfig')}
        description={t('rcApprovalConfigDesc')}
        value={settings.approvalConfigId ?? 'none'}
        options={[{ value: 'none', label: t('rcDirectPublish') }]}
        onChange={(v) => onChange({ approvalConfigId: v === 'none' ? null : v })}
      />
      <BooleanRow
        label={t('rcAutoDelivery')}
        description={t('rcAutoDeliveryDesc')}
        value={settings.autoDelivery}
        onChange={(v) => onChange({ autoDelivery: v })}
      />
      {settings.autoDelivery && (
        <SelectRow
          label={t('rcDeliveryChannel')}
          value={settings.deliveryChannel}
          options={[
            { value: 'email', label: t('channelEmail') },
            { value: 'whatsapp', label: t('channelWhatsApp') },
            { value: 'both', label: t('channelBoth') },
          ]}
          onChange={(v) =>
            onChange({ deliveryChannel: v as 'email' | 'whatsapp' | 'both' })
          }
        />
      )}

      <SubSectionCard title={t('rcComparativeIndicators')}>
        <BooleanRow
          label={t('rcShowComparativeLabel')}
          description={t('rcShowComparativeLabelDesc')}
          value={settings.showComparativeLabel}
          onChange={(v) => onChange({ showComparativeLabel: v })}
        />
        <BooleanRow
          label={t('rcShowPercentile')}
          description={t('rcShowPercentileDesc')}
          value={settings.showPercentile}
          onChange={(v) => onChange({ showPercentile: v })}
        />
        <BooleanRow
          label={t('rcShowTopThreeRank')}
          description={t('rcShowTopThreeRankDesc')}
          value={settings.showTopThreeRank}
          onChange={(v) => onChange({ showTopThreeRank: v })}
        />
      </SubSectionCard>

      <SubSectionCard title={t('rcParentAcknowledgment')}>
        <BooleanRow
          label={t('rcRequireAcknowledgment')}
          description={t('rcRequireAcknowledgmentDesc')}
          value={settings.requireParentAcknowledgment}
          onChange={(v) => onChange({ requireParentAcknowledgment: v })}
        />
        {settings.requireParentAcknowledgment && (
          <NumberRow
            label={t('rcAcknowledgmentReminderDays')}
            description={t('rcAcknowledgmentReminderDaysDesc')}
            value={settings.acknowledgmentReminderDays}
            onChange={(v) => onChange({ acknowledgmentReminderDays: v ?? 7 })}
            min={1}
          />
        )}
      </SubSectionCard>

      <SubSectionCard title={t('rcAutoGenerate')}>
        <BooleanRow
          label={t('rcAutoGenerateEnabled')}
          description={t('rcAutoGenerateEnabledDesc')}
          value={settings.autoGenerateReportCards}
          onChange={(v) => onChange({ autoGenerateReportCards: v })}
        />
        {settings.autoGenerateReportCards && (
          <NumberRow
            label={t('rcAutoGenerateDaysAfterPeriodEnd')}
            description={t('rcAutoGenerateDaysAfterPeriodEndDesc')}
            value={settings.autoGenerateDaysAfterPeriodEnd}
            onChange={(v) => onChange({ autoGenerateDaysAfterPeriodEnd: v ?? 1 })}
            min={0}
          />
        )}
      </SubSectionCard>
    </SectionCard>
  );
}
