// ─── Settings Types ───────────────────────────────────────────────────────────

export interface PatternDetectionSettings {
  enabled: boolean;
  excessiveAbsenceThreshold: number;
  excessiveAbsenceWindowDays: number;
  recurringDayThreshold: number;
  recurringDayWindowDays: number;
  tardinessThreshold: number;
  tardinessWindowDays: number;
  parentNotificationMode: 'auto' | 'manual';
}

export interface AttendanceSettings {
  allowTeacherAmendment: boolean;
  autoLockAfterDays: number | null;
  pendingAlertTimeHour: number;
  workDays: number[];
  defaultPresentEnabled: boolean;
  notifyParentOnAbsence: boolean;
  patternDetection: PatternDetectionSettings;
}

export interface AiSettings {
  enabled: boolean;
  commentStyle: 'formal' | 'warm' | 'balanced';
  commentSampleReference: string | null;
  commentTargetWordCount: number;
  aiProgressSummariesEnabled: boolean;
  aiGradingDailyLimit: number;
}

export interface GradebookSettings {
  defaultMissingGradePolicy: 'exclude' | 'zero';
  requireGradeComment: boolean;
  formativeWeightCap: number | null;
  formativeIncludedInPeriodGrade: boolean;
  gpaPrecision: 1 | 2;
  gpaScaleLabel: string;
  atRiskDetectionEnabled: boolean;
  atRiskDetectionFrequency: 'daily' | 'weekly';
  gradingConsistencyThreshold: number;
  requireApprovalForMarkingSchemes: boolean;
}

export interface AdmissionsSettings {
  requireApprovalForAcceptance: boolean;
}

export interface FinanceSettings {
  requireApprovalForInvoiceIssue: boolean;
  defaultPaymentTermDays: number;
  allowPartialPayment: boolean;
  paymentReminderEnabled: boolean;
  dueSoonReminderDays: number;
  finalNoticeAfterDays: number;
  reminderChannel: 'email' | 'whatsapp' | 'both';
  autoIssueRecurringInvoices: boolean;
  lateFeeEnabled: boolean;
  defaultLateFeeConfigId: string | null;
  paymentApportionmentStrategy: 'proportional' | 'sequential';
}

export interface CommunicationsSettings {
  primaryOutboundChannel: 'email' | 'whatsapp';
  requireApprovalForAnnouncements: boolean;
}

export interface PayrollSettings {
  requireApprovalForNonPrincipal: boolean;
  defaultBonusMultiplier: number;
  autoPopulateClassCounts: boolean;
  payDay: number;
  payrollPreparationLeadDays: number;
  autoCreatePayrollRun: boolean;
  autoCreateRunDay: number;
  payrollAccountantEmail: string;
  autoSendPayslips: boolean;
  payslipDeliveryMethod: 'email' | 'in_app' | 'both';
}

export interface GeneralSectionSettings {
  parentPortalEnabled: boolean;
  attendanceVisibleToParents: boolean;
  gradesVisibleToParents: boolean;
  inquiryStaleHours: number;
}

export interface SchedulingPreferenceWeights {
  low: number;
  medium: number;
  high: number;
}

export interface SchedulingGlobalSoftWeights {
  evenSubjectSpread: number;
  minimiseTeacherGaps: number;
  roomConsistency: number;
  workloadBalance: number;
}

export interface SchedulingSettings {
  teacherWeeklyMaxPeriods: number | null;
  autoSchedulerEnabled: boolean;
  requireApprovalForNonPrincipal: boolean;
  maxSolverDurationSeconds: number;
  preferenceWeights: SchedulingPreferenceWeights;
  globalSoftWeights: SchedulingGlobalSoftWeights;
  autoAssignUrgentSubstitutions: boolean;
  urgentThresholdMinutes: number;
  notifyTeachersOnScheduleChange: boolean;
  scheduleChangeNotificationChannel: 'in_app' | 'email' | 'both';
}

export interface ApprovalsSettings {
  expiryDays: number;
  reminderAfterHours: number;
}

export interface ComplianceSettings {
  auditLogRetentionMonths: number;
}

export interface ReportCardsSettings {
  approvalConfigId: string | null;
  autoDelivery: boolean;
  deliveryChannel: 'email' | 'whatsapp' | 'both';
  showComparativeLabel: boolean;
  showPercentile: boolean;
  showTopThreeRank: boolean;
  requireParentAcknowledgment: boolean;
  acknowledgmentReminderDays: number;
  autoGenerateReportCards: boolean;
  autoGenerateDaysAfterPeriodEnd: number;
}

export interface TenantSettings {
  general: GeneralSectionSettings;
  attendance: AttendanceSettings;
  gradebook: GradebookSettings;
  admissions: AdmissionsSettings;
  finance: FinanceSettings;
  communications: CommunicationsSettings;
  payroll: PayrollSettings;
  scheduling: SchedulingSettings;
  approvals: ApprovalsSettings;
  compliance: ComplianceSettings;
  ai: AiSettings;
  reportCards: ReportCardsSettings;
}

export type SettingsSectionKey = keyof TenantSettings;

export interface SettingsApiResponse {
  data?: TenantSettings;
  warnings?: string[];
}

// ─── Defaults ─────────────────────────────────────────────────────────────────

export const DEFAULT_SETTINGS: TenantSettings = {
  general: {
    parentPortalEnabled: true,
    attendanceVisibleToParents: true,
    gradesVisibleToParents: true,
    inquiryStaleHours: 48,
  },
  attendance: {
    allowTeacherAmendment: false,
    autoLockAfterDays: null,
    pendingAlertTimeHour: 14,
    workDays: [1, 2, 3, 4, 5],
    defaultPresentEnabled: false,
    notifyParentOnAbsence: false,
    patternDetection: {
      enabled: false,
      excessiveAbsenceThreshold: 5,
      excessiveAbsenceWindowDays: 14,
      recurringDayThreshold: 3,
      recurringDayWindowDays: 30,
      tardinessThreshold: 4,
      tardinessWindowDays: 14,
      parentNotificationMode: 'manual',
    },
  },
  gradebook: {
    defaultMissingGradePolicy: 'exclude',
    requireGradeComment: false,
    formativeWeightCap: null,
    formativeIncludedInPeriodGrade: true,
    gpaPrecision: 2,
    gpaScaleLabel: 'GPA',
    atRiskDetectionEnabled: false,
    atRiskDetectionFrequency: 'weekly',
    gradingConsistencyThreshold: 15,
    requireApprovalForMarkingSchemes: false,
  },
  admissions: {
    requireApprovalForAcceptance: true,
  },
  finance: {
    requireApprovalForInvoiceIssue: false,
    defaultPaymentTermDays: 30,
    allowPartialPayment: true,
    paymentReminderEnabled: true,
    dueSoonReminderDays: 3,
    finalNoticeAfterDays: 14,
    reminderChannel: 'email',
    autoIssueRecurringInvoices: false,
    lateFeeEnabled: false,
    defaultLateFeeConfigId: null,
    paymentApportionmentStrategy: 'proportional' as const,
  },
  communications: {
    primaryOutboundChannel: 'email',
    requireApprovalForAnnouncements: true,
  },
  payroll: {
    requireApprovalForNonPrincipal: true,
    defaultBonusMultiplier: 1.0,
    autoPopulateClassCounts: true,
    payDay: 25,
    payrollPreparationLeadDays: 5,
    autoCreatePayrollRun: false,
    autoCreateRunDay: 1,
    payrollAccountantEmail: '',
    autoSendPayslips: false,
    payslipDeliveryMethod: 'email',
  },
  scheduling: {
    teacherWeeklyMaxPeriods: null,
    autoSchedulerEnabled: true,
    requireApprovalForNonPrincipal: true,
    maxSolverDurationSeconds: 120,
    preferenceWeights: { low: 1, medium: 2, high: 3 },
    globalSoftWeights: {
      evenSubjectSpread: 2,
      minimiseTeacherGaps: 1,
      roomConsistency: 1,
      workloadBalance: 1,
    },
    autoAssignUrgentSubstitutions: false,
    urgentThresholdMinutes: 60,
    notifyTeachersOnScheduleChange: true,
    scheduleChangeNotificationChannel: 'both',
  },
  approvals: {
    expiryDays: 7,
    reminderAfterHours: 48,
  },
  compliance: {
    auditLogRetentionMonths: 36,
  },
  ai: {
    enabled: false,
    commentStyle: 'balanced',
    commentSampleReference: null,
    commentTargetWordCount: 100,
    aiProgressSummariesEnabled: false,
    aiGradingDailyLimit: 200,
  },
  reportCards: {
    approvalConfigId: null,
    autoDelivery: true,
    deliveryChannel: 'email',
    showComparativeLabel: false,
    showPercentile: false,
    showTopThreeRank: false,
    requireParentAcknowledgment: false,
    acknowledgmentReminderDays: 7,
    autoGenerateReportCards: false,
    autoGenerateDaysAfterPeriodEnd: 1,
  },
};
