#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Communications Overhaul — Production Cutover Script
#
# DO NOT RUN AS-IS. This is a checklist + reference for the user to follow
# AFTER the communications-overhaul work is merged into main.
#
# Each step is documented; the user inspects, adapts, and runs each block
# explicitly. There is no `bash production-cutover.sh` invocation.
#
# Generated by Impl 13 of the Communications Overhaul rebuild.
# Source of truth: communicationnew/cutover/production-cutover.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

cat <<'BANNER'

┌────────────────────────────────────────────────────────────────────┐
│   Communications Overhaul — Production Cutover Script              │
│                                                                    │
│   This script is a CHECKLIST. Read every step before running.      │
│   Do NOT execute the whole file in one go.                         │
│   Each step starts with `# STEP N`. Run step-by-step.              │
└────────────────────────────────────────────────────────────────────┘

BANNER

# ─── STEP 1 — Backup production DB ──────────────────────────────────────────
# Before any backfill, take a logical pg_dump.
#
#   ssh root@46.62.244.139
#   sudo -u postgres pg_dump -Fc -f /var/backups/comms-cutover-$(date +%Y%m%d_%H%M).dump school_platform
#
# Verify the dump file size is non-trivial (> 100 MB on a real tenant load).

# ─── STEP 2 — Verify migrations are already applied ─────────────────────────
# When the user merges main, GitHub Actions runs `scripts/deploy-production.sh`
# which calls `prisma migrate deploy`. The 8 new tables (Impl 01) and the
# permission rows (Impl 02 seed) ship through CI, NOT through this script.
#
# This step is a sanity check, not an action:
#
#   ssh root@46.62.244.139
#   cd /var/www/edupod/current
#   sudo -u edupod npx prisma migrate status
#
# Expect: "Database schema is up to date."
#
# Verify the new tables exist:
#   sudo -u postgres psql school_platform -c "\d tenant_email_configs"
#   sudo -u postgres psql school_platform -c "\d tenant_sms_configs"
#   sudo -u postgres psql school_platform -c "\d tenant_whatsapp_configs"
#   sudo -u postgres psql school_platform -c "\d notification_suppression_list"
#   sudo -u postgres psql school_platform -c "\d tenant_email_domains"
#   sudo -u postgres psql school_platform -c "\d whatsapp_templates"
#   sudo -u postgres psql school_platform -c "\d whatsapp_service_windows"
#   sudo -u postgres psql school_platform -c "\d notification_webhook_events"
#
# All 8 tables must exist with FORCE ROW LEVEL SECURITY enabled.

# ─── STEP 3 — Backfill permissions on existing production tenants ───────────
# Impl 02's script grants `configuration.communications.{view,manage}` to
# `school_owner` + `school_principal` on every existing tenant.
#
#   ssh edupod@46.62.244.139
#   cd /var/www/edupod/current
#   pnpm --filter @school/prisma backfill:comms-permissions
#
# Expect: "Total grants added: N" where N = (tenants × 4) for the first run.
# Re-running: "Total grants added: 0" — proven idempotency.

# ─── STEP 4 — Provision prod-tenant-credentials.json ────────────────────────
# This file is gitignored. Populate it from production secret stores.
#
#   ssh edupod@46.62.244.139
#   cd /var/www/edupod/current/packages/prisma/scripts
#   cp dev-tenant-credentials.example.json prod-tenant-credentials.json
#   # Edit prod-tenant-credentials.json — populate with REAL Resend / Twilio keys
#   # for each tenant. Pull from 1Password / AWS Secrets Manager / wherever.
#   chmod 600 prod-tenant-credentials.json
#
# The verification_recipients block should be a real ops contact — someone
# who will receive every test send and confirm receipt.

# ─── STEP 5 — Run the credential backfill against production ────────────────
# Same script as dev, different config file.
#
#   cd /var/www/edupod/current
#   CREDENTIALS_FILE=packages/prisma/scripts/prod-tenant-credentials.json \
#     pnpm tsx packages/prisma/scripts/backfill-tenant-communications-configs.ts
#
# Expect: 15 rows written (5 tenants × 3 channels), every encrypted column
# passes the {iv}:{tag}:{ct} shape assertion.
#
# CRITICAL: ENCRYPTION_KEY_V1 must be set in production .env before running.
# Verify before invoking:
#   sudo -u edupod cat /var/www/edupod/.env | grep ^ENCRYPTION_KEY

# ─── STEP 6 — Submit comms.verify WhatsApp template to Twilio ───────────────
# The dev backfill set `twilio_template_sid='HX_DEV_VERIFY'`. Production needs
# a real Twilio template approval per tenant.
#
# For each tenant:
#   1. Use Impl 08's submission flow to register `comms.verify` with Twilio
#      (POST /v1/whatsapp-templates with category=authentication, body=
#      "EduPod WhatsApp verification — your school's WhatsApp integration is
#      wired up correctly.")
#   2. Wait for Twilio approval (manual queue, typically 1–24 hours).
#   3. The cron `comms:whatsapp-template-sync` (Impl 08) polls every 15 min
#      and flips `whatsapp_templates.status` to `approved` once Twilio
#      acknowledges. Verify with:
#
#        SELECT tenant_id, template_key, status, twilio_template_sid
#          FROM whatsapp_templates
#         WHERE template_key = 'comms.verify'
#         ORDER BY tenant_id;
#
#      All rows must show `status='approved'` and a real `HX...` sid (not
#      the dev placeholder `HX_DEV_VERIFY`).

# ─── STEP 7 — Register email domains via Resend ─────────────────────────────
# For each production tenant, register the sender domain via Impl 07's
# endpoint. This populates DNS records the tenant must publish.
#
#   curl -X POST https://app.edupod.app/api/v1/email-domains \
#     -H "Authorization: Bearer <tenant-owner-token>" \
#     -H "content-type: application/json" \
#     -d '{"domain":"<tenant-sender-domain>"}'
#
# Capture the DNS record list from the response. Send the records to the
# tenant for them to publish in their DNS provider.
#
# The cron `comms:domain-verification-refresh` (Impl 07) polls Resend every
# 30 min and flips `tenant_email_domains.status` to `verified` once SPF +
# DKIM + DMARC are all green. Manual refresh:
#
#   curl -X POST https://app.edupod.app/api/v1/email-domains/<id>/refresh \
#     -H "Authorization: Bearer <tenant-owner-token>"
#
# Verify all tenant domains are verified before the next step:
#
#   SELECT tenant_id, domain, status, verified_at
#     FROM tenant_email_domains
#    ORDER BY tenant_id;

# ─── STEP 8 — Confirm bypass flag is NOT set on production ──────────────────
# Critical safety check. The dev bypass flag must NEVER be true in prod.
#
#   ssh root@46.62.244.139
#   sudo -u edupod cat /var/www/edupod/.env | grep COMMS_BYPASS_DOMAIN_VERIFICATION_FOR_DEV
#
# Expect: either no output (flag unset) or `COMMS_BYPASS_DOMAIN_VERIFICATION_FOR_DEV=false`.
# If the flag is `true` in production, STOP — that is a deliverability incident
# waiting to happen. Fix .env before proceeding.

# ─── STEP 9 — Restart API and worker via PM2 ────────────────────────────────
# After credential backfill, the running API + worker may have stale cached
# Resend / Twilio clients. Restart to pick up the new tenant configs.
#
#   ssh edupod@46.62.244.139
#   pm2 restart edupod-api edupod-worker
#   pm2 logs edupod-api --lines 50      # watch for "tenant config loaded" log lines
#   pm2 logs edupod-worker --lines 50

# ─── STEP 10 — Smoke test each tenant ──────────────────────────────────────
# For each production tenant, run the verifier flow:
#
#   1. Login as the tenant owner
#   2. Visit /settings/communications — confirm all 3 channels show "Configured"
#   3. Click "Send test message" on each channel — recipient is the prod ops
#      contact from STEP 4
#   4. Verify receipt in the ops contact's inbox / phone
#
# Alternatively, drive via the verifier script pointed at production:
#
#   API_BASE=https://app.edupod.app \
#     CREDENTIALS_FILE=packages/prisma/scripts/prod-tenant-credentials.json \
#     pnpm tsx packages/prisma/scripts/verify-tenant-communications-configs.ts
#
# Expect: 15/15 succeeded. Any failure → STOP, investigate that tenant's
# credentials, rerun.

# ─── STEP 11 — Monitor first 24 hours ───────────────────────────────────────
# Check Sentry for new comms-tagged errors:
#   ./scripts/sentry-cli.sh new-events-since "$(date -u -v-1H +%Y-%m-%dT%H:%M:%SZ)"
#
# Check Grafana dashboard `docs/operations/dashboards/communications.json`:
#   - notifications_dispatched_total — expect normal volume per tenant
#   - notifications_suppressed_total — expect zero or near-zero
#   - notifications_webhook_received_total — expect Resend + Twilio events
#
# Check production logs for `tenant_id` tag presence on every comms log line
# (Impl 10 enforces structured logging through CommsLoggerService).

echo ""
echo "Cutover complete. Update communicationnew/IMPLEMENTATION_LOG.md §5 with the cutover record."
echo ""
