"""V3 pydantic models — CP-SAT-native solver contract.

Mirrors ``packages/shared/src/scheduler/types-v3.ts``. Field names,
optionality, and literal sets must stay byte-compatible. Drift is
asserted by the round-trip test in ``apps/solver-py/tests/test_schema_v3_roundtrip.py``
and the TypeScript-side contract test.
"""

from solver_py.schema.v3.input import (
    BreakGroupV3,
    ClassPreferenceV3,
    ClassV3,
    ConstraintSnapshotEntry,
    DemandV3,
    GlobalSoftWeightsV3,
    PeriodSlotV3,
    PeriodTypeV3,
    PinnedAssignmentV3,
    PreferencePriorityV3,
    PreferencesV3,
    PreferenceTypeV3,
    PreferenceWeightsV3,
    RoomClosureV3,
    RoomV3,
    SolverInputV3,
    SolverSettingsV3,
    StudentOverlapV3,
    SubjectV3,
    SupervisionModeV3,
    TeacherAvailabilityV3,
    TeacherCompetencyV3,
    TeacherPreferenceV3,
    TeacherV3,
)
from solver_py.schema.v3.output import (
    AssignmentV3,
    EarlyStopReasonV3,
    ObjectiveBreakdownEntry,
    PreferenceBreakdownEntryV3,
    PreferenceSatisfactionV3,
    QualityMetricRangeV3,
    QualityMetricsV3,
    RoomAssignmentSource,
    SolverOutputV3,
    SolveStatusV3,
    UnassignedDemandV3,
)

__all__ = [
    "AssignmentV3",
    "BreakGroupV3",
    "ClassPreferenceV3",
    "ClassV3",
    "ConstraintSnapshotEntry",
    "DemandV3",
    "EarlyStopReasonV3",
    "GlobalSoftWeightsV3",
    "ObjectiveBreakdownEntry",
    "PeriodSlotV3",
    "PeriodTypeV3",
    "PinnedAssignmentV3",
    "PreferenceBreakdownEntryV3",
    "PreferencePriorityV3",
    "PreferenceSatisfactionV3",
    "PreferenceTypeV3",
    "PreferenceWeightsV3",
    "PreferencesV3",
    "QualityMetricRangeV3",
    "QualityMetricsV3",
    "RoomAssignmentSource",
    "RoomClosureV3",
    "RoomV3",
    "SolveStatusV3",
    "SolverInputV3",
    "SolverOutputV3",
    "SolverSettingsV3",
    "StudentOverlapV3",
    "SubjectV3",
    "SupervisionModeV3",
    "TeacherAvailabilityV3",
    "TeacherCompetencyV3",
    "TeacherPreferenceV3",
    "TeacherV3",
    "UnassignedDemandV3",
]
