export const QUEUE_NAMES = {
  ADMISSIONS: 'admissions',
  APPROVALS: 'approvals',
  ATTENDANCE: 'attendance',
  BEHAVIOUR: 'behaviour',
  COMPLIANCE: 'compliance',
  EARLY_WARNING: 'early-warning',
  ENGAGEMENT: 'engagement',
  FINANCE: 'finance',
  GRADEBOOK: 'gradebook',
  HOMEWORK: 'homework',
  IMPORTS: 'imports',
  NOTIFICATIONS: 'notifications',
  PASTORAL: 'pastoral',
  PAYROLL: 'payroll',
  PDF_RENDERING: 'pdf-rendering',
  REGULATORY: 'regulatory',
  REPORTS: 'reports',
  SCHEDULING: 'scheduling',
  SEARCH_SYNC: 'search-sync',
  SECURITY: 'security',
  WELLBEING: 'wellbeing',
} as const;

export type QueueName = (typeof QUEUE_NAMES)[keyof typeof QUEUE_NAMES];
