#!/usr/bin/env node
/**
 * coverage-by-module.ts
 *
 * Reads coverage/coverage-summary.json (generated by Jest with --coverageReporters=json)
 * and aggregates per-file coverage into per-NestJS-module totals.
 *
 * NOTE: coverage-summary.json now reflects ALL source files thanks to
 * `collectCoverageFrom` in jest.config.js. Files with zero tests show 0%
 * instead of being invisible — this gives truthful per-module coverage.
 *
 * Outputs a formatted table to stdout and saves to coverage/module-coverage-report.txt.
 *
 * Run via: tsx scripts/coverage-by-module.ts
 * Or via:  pnpm --filter @school/api coverage:modules
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';

// ─── Types ────────────────────────────────────────────────────────────────────

interface CoverageEntry {
  total: number;
  covered: number;
  skipped: number;
  pct: number;
}

interface FileSummary {
  lines: CoverageEntry;
  functions: CoverageEntry;
  branches: CoverageEntry;
  statements: CoverageEntry;
}

interface CoverageSummary {
  [filePath: string]: FileSummary;
}

interface ModuleAccumulator {
  lines: { total: number; covered: number };
  functions: { total: number; covered: number };
  branches: { total: number; covered: number };
  statements: { total: number; covered: number };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function pct(covered: number, total: number): string {
  if (total === 0) return '  N/A  ';
  return `${((covered / total) * 100).toFixed(1)}%`;
}

function padEnd(str: string, len: number): string {
  return str.length >= len ? str : str + ' '.repeat(len - str.length);
}

function padStart(str: string, len: number): string {
  return str.length >= len ? str : ' '.repeat(len - str.length) + str;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main(): void {
  // Resolve paths relative to apps/api (where jest runs from)
  // When invoked via `coverage:modules`, cwd is apps/api
  const cwd = process.cwd();
  const summaryPath = resolve(cwd, 'coverage', 'coverage-summary.json');

  if (!existsSync(summaryPath)) {
    console.error(`[coverage-by-module] coverage-summary.json not found at: ${summaryPath}`);
    console.error('[coverage-by-module] Run jest with --coverage --coverageReporters=json first.');
    process.exit(1);
  }

  const raw = readFileSync(summaryPath, 'utf-8');
  const summary = JSON.parse(raw) as CoverageSummary;

  // ─── Aggregate by module ──────────────────────────────────────────────────

  const modules = new Map<string, ModuleAccumulator>();

  for (const [filePath, data] of Object.entries(summary)) {
    // Skip the top-level "total" entry
    if (filePath === 'total') continue;

    // Match src/modules/{name}/ anywhere in the path
    const match = /src\/modules\/([^/]+)\//.exec(filePath);
    const moduleName = match ? match[1] : '_other';

    if (!modules.has(moduleName)) {
      modules.set(moduleName, {
        lines: { total: 0, covered: 0 },
        functions: { total: 0, covered: 0 },
        branches: { total: 0, covered: 0 },
        statements: { total: 0, covered: 0 },
      });
    }

    const acc = modules.get(moduleName) as ModuleAccumulator;
    acc.lines.total += data.lines.total;
    acc.lines.covered += data.lines.covered;
    acc.functions.total += data.functions.total;
    acc.functions.covered += data.functions.covered;
    acc.branches.total += data.branches.total;
    acc.branches.covered += data.branches.covered;
    acc.statements.total += data.statements.total;
    acc.statements.covered += data.statements.covered;
  }

  // ─── Build table ──────────────────────────────────────────────────────────

  const sortedModules = [...modules.entries()].sort(([a], [b]) => a.localeCompare(b));

  const COL_MODULE = 22;
  const COL_STAT = 8;

  const header =
    padEnd('Module', COL_MODULE) +
    '| ' +
    padStart('Lines', COL_STAT) +
    ' | ' +
    padStart('Funcs', COL_STAT) +
    ' | ' +
    padStart('Branch', COL_STAT) +
    ' | ' +
    padStart('Stmts', COL_STAT);

  const divider =
    '-'.repeat(COL_MODULE) +
    '+-' +
    '-'.repeat(COL_STAT + 1) +
    '-+-' +
    '-'.repeat(COL_STAT + 1) +
    '-+-' +
    '-'.repeat(COL_STAT + 1) +
    '-+-' +
    '-'.repeat(COL_STAT);

  const rows = sortedModules.map(([name, acc]) => {
    const lines = pct(acc.lines.covered, acc.lines.total);
    const funcs = pct(acc.functions.covered, acc.functions.total);
    const branches = pct(acc.branches.covered, acc.branches.total);
    const stmts = pct(acc.statements.covered, acc.statements.total);

    return (
      padEnd(name, COL_MODULE) +
      '| ' +
      padStart(lines, COL_STAT) +
      ' | ' +
      padStart(funcs, COL_STAT) +
      ' | ' +
      padStart(branches, COL_STAT) +
      ' | ' +
      padStart(stmts, COL_STAT)
    );
  });

  // Overall totals row
  const totalAcc: ModuleAccumulator = {
    lines: { total: 0, covered: 0 },
    functions: { total: 0, covered: 0 },
    branches: { total: 0, covered: 0 },
    statements: { total: 0, covered: 0 },
  };
  for (const [, acc] of sortedModules) {
    totalAcc.lines.total += acc.lines.total;
    totalAcc.lines.covered += acc.lines.covered;
    totalAcc.functions.total += acc.functions.total;
    totalAcc.functions.covered += acc.functions.covered;
    totalAcc.branches.total += acc.branches.total;
    totalAcc.branches.covered += acc.branches.covered;
    totalAcc.statements.total += acc.statements.total;
    totalAcc.statements.covered += acc.statements.covered;
  }

  const totalRow =
    padEnd('TOTAL', COL_MODULE) +
    '| ' +
    padStart(pct(totalAcc.lines.covered, totalAcc.lines.total), COL_STAT) +
    ' | ' +
    padStart(pct(totalAcc.functions.covered, totalAcc.functions.total), COL_STAT) +
    ' | ' +
    padStart(pct(totalAcc.branches.covered, totalAcc.branches.total), COL_STAT) +
    ' | ' +
    padStart(pct(totalAcc.statements.covered, totalAcc.statements.total), COL_STAT);

  const timestamp = new Date().toISOString();
  const report = [
    `Module Coverage Report — generated ${timestamp}`,
    '',
    header,
    divider,
    ...rows,
    divider,
    totalRow,
    '',
  ].join('\n');

  // ─── Output ───────────────────────────────────────────────────────────────

  console.log('\n' + report);

  const outputPath = resolve(cwd, 'coverage', 'module-coverage-report.txt');
  const outputDir = dirname(outputPath);
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }
  writeFileSync(outputPath, report, 'utf-8');
  console.log(`[coverage-by-module] Report saved to: ${outputPath}`);
}

main();
