/* eslint-disable school/no-raw-sql-outside-rls -- RLS e2e tests require direct SQL for setup/teardown */
/**
 * RLS Leakage Tests — Phase 8 (Audit Logs, Compliance, Imports, Search Index)
 *
 * Verifies that tenant isolation holds at both the API level and the database
 * layer for all P8 entities: compliance_requests, import_jobs,
 * search_index_status.
 *
 * Special handling:
 *   - audit_logs has dual-policy (nullable tenant_id): tenant B cannot see
 *     tenant A rows but CAN see platform rows (NULL tenant_id) via the
 *     platform admin endpoint.
 *
 * Two test categories:
 *   1. API-level — create data as Al Noor (Tenant A), authenticate as Cedar
 *      (Tenant B), call each endpoint, assert only Cedar data is returned.
 *   2. Table-level — open a Prisma transaction as the rls_test_user_p8b role,
 *      SET LOCAL app.current_tenant_id to Cedar, query each table, and assert
 *      that no Al Noor rows are returned.
 */

import { INestApplication } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

import {
  AL_NOOR_DOMAIN,
  AL_NOOR_OWNER_EMAIL,
  CEDAR_DOMAIN,
  CEDAR_OWNER_EMAIL,
  DEV_PASSWORD,
  PLATFORM_ADMIN_EMAIL,
  authGet,
  authPost,
  closeTestApp,
  createTestApp,
  getAuthToken,
  login,
} from './helpers';

// ─── Constants ───────────────────────────────────────────────────────────────

let AL_NOOR_TENANT_ID: string;
let CEDAR_TENANT_ID: string;
const RLS_TEST_ROLE = 'rls_test_user_p8b';

/** Unique marker embedded in Al Noor data for leakage detection. */
const UNIQUE_MARKER = `RlsP8bLeak_${Date.now()}`;

// ─── Suite ───────────────────────────────────────────────────────────────────

jest.setTimeout(120_000);

describe('P8 RLS Leakage — Audit, Compliance, Imports, Search Index (e2e)', () => {
  let app: INestApplication;
  let alNoorToken: string;
  let cedarToken: string;
  let platformToken: string;
  let alNoorUserId: string;

  /** Direct Prisma client for table-level RLS tests and data setup. */
  let directPrisma: PrismaClient;

  // IDs created as Al Noor
  let alNoorAuditLogId: string;
  let platformAuditLogId: string;
  let complianceRequestId: string;
  let importJobId: string;
  let searchIndexStatusId: string;

  beforeAll(async () => {
    app = await createTestApp();

    // Authenticate as both tenants + platform admin
    const alNoorLogin = await login(app, AL_NOOR_OWNER_EMAIL, DEV_PASSWORD, AL_NOOR_DOMAIN);
    alNoorToken = alNoorLogin.accessToken;
    alNoorUserId = (alNoorLogin.user as Record<string, string>).id!;

    const cedarLogin = await login(app, CEDAR_OWNER_EMAIL, DEV_PASSWORD, CEDAR_DOMAIN);
    cedarToken = cedarLogin.accessToken;

    platformToken = await getAuthToken(app, PLATFORM_ADMIN_EMAIL);

    // ── Direct Prisma for data setup / table-level tests ──────────────────

    directPrisma = new PrismaClient({
      datasources: {
        db: { url: process.env.DATABASE_URL },
      },
    });
    await directPrisma.$connect();

    // Dynamically resolve tenant IDs (they are auto-generated by seed)
    const tenants = await directPrisma.tenant.findMany({
      where: { slug: { in: ['al-noor', 'cedar'] } },
      select: { id: true, slug: true },
    });
    AL_NOOR_TENANT_ID = tenants.find((t) => t.slug === 'al-noor')!.id;
    CEDAR_TENANT_ID = tenants.find((t) => t.slug === 'cedar')!.id;

    // ── Create Al Noor audit log data (direct insert for precise control) ─

    // 1. Tenant-scoped audit log for Al Noor
    const alLogResult: Array<{ id: string }> = await directPrisma.$queryRawUnsafe(
      `
      INSERT INTO audit_logs (tenant_id, actor_user_id, entity_type, action, metadata_json, ip_address)
      VALUES ($1::uuid, $2::uuid, $3, 'rls_test_action', '{}'::jsonb, '127.0.0.1')
      RETURNING id::text
    `,
      AL_NOOR_TENANT_ID,
      alNoorUserId,
      `rls_test_p8b_${UNIQUE_MARKER}`,
    );
    alNoorAuditLogId = alLogResult[0]!.id;

    // 2. Platform-level audit log (tenant_id = NULL)
    const platformLogResult: Array<{ id: string }> = await directPrisma.$queryRawUnsafe(
      `
      INSERT INTO audit_logs (tenant_id, actor_user_id, entity_type, action, metadata_json, ip_address)
      VALUES (NULL, NULL, $1, $2, '{}'::jsonb, $3)
      RETURNING id::text
    `,
      `platform_rls_test_p8b_${UNIQUE_MARKER}`,
      'platform_test_action',
      '127.0.0.1',
    );
    platformAuditLogId = platformLogResult[0]!.id;

    // ── Create Al Noor compliance request data ────────────────────────────

    const crRes = await authPost(
      app,
      '/api/v1/compliance-requests',
      alNoorToken,
      {
        request_type: 'access_export',
        subject_type: 'user',
        subject_id: alNoorUserId,
      },
      AL_NOOR_DOMAIN,
    ).expect(201);
    const crBody = crRes.body.data ?? crRes.body;
    complianceRequestId = crBody.id;

    // ── Create Al Noor import job (direct insert to avoid file upload) ────

    const ijResult: Array<{ id: string }> = await directPrisma.$queryRawUnsafe(
      `
      INSERT INTO import_jobs (tenant_id, import_type, status, summary_json, created_by_user_id)
      VALUES ($1::uuid, 'students', 'uploaded', '{"total_rows": 5, "failed": 0}'::jsonb, $2::uuid)
      RETURNING id::text
    `,
      AL_NOOR_TENANT_ID,
      alNoorUserId,
    );
    importJobId = ijResult[0]!.id;

    // ── Create Al Noor search index status (direct insert) ───────────────

    const sisResult: Array<{ id: string }> = await directPrisma.$queryRawUnsafe(
      `
      INSERT INTO search_index_status (tenant_id, entity_type, entity_id, index_status)
      VALUES ($1::uuid, 'student', gen_random_uuid(), 'pending')
      RETURNING id::text
    `,
      AL_NOOR_TENANT_ID,
    );
    searchIndexStatusId = sisResult[0]!.id;

    // ── Table-level RLS setup ─────────────────────────────────────────────

    await directPrisma.$executeRawUnsafe(
      `DO $$ BEGIN
         CREATE ROLE ${RLS_TEST_ROLE} NOLOGIN;
       EXCEPTION WHEN duplicate_object THEN NULL;
       END $$`,
    );
    await directPrisma.$executeRawUnsafe(`GRANT USAGE ON SCHEMA public TO ${RLS_TEST_ROLE}`);
    await directPrisma.$executeRawUnsafe(
      `GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${RLS_TEST_ROLE}`,
    );
  }, 120_000);

  afterAll(async () => {
    if (directPrisma) {
      // Clean up test data
      try {
        await directPrisma.$executeRawUnsafe(
          `DELETE FROM audit_logs WHERE id IN ($1::uuid, $2::uuid)`,
          alNoorAuditLogId,
          platformAuditLogId,
        );
        await directPrisma.$executeRawUnsafe(
          `DELETE FROM compliance_requests WHERE id = $1::uuid`,
          complianceRequestId,
        );
        await directPrisma.$executeRawUnsafe(
          `DELETE FROM import_jobs WHERE id = $1::uuid`,
          importJobId,
        );
        await directPrisma.$executeRawUnsafe(
          `DELETE FROM search_index_status WHERE id = $1::uuid`,
          searchIndexStatusId,
        );
      } catch (err) {
        console.error('[p8 RLS leakage data cleanup]', err);
      }

      // Clean up RLS test role
      try {
        await directPrisma.$executeRawUnsafe(
          `REVOKE ALL ON ALL TABLES IN SCHEMA public FROM ${RLS_TEST_ROLE}`,
        );
        await directPrisma.$executeRawUnsafe(`REVOKE USAGE ON SCHEMA public FROM ${RLS_TEST_ROLE}`);
        await directPrisma.$executeRawUnsafe(`DROP ROLE IF EXISTS ${RLS_TEST_ROLE}`);
      } catch (err) {
        console.error('[p8 RLS leakage role cleanup]', err);
      }
      await directPrisma.$disconnect();
    }
    await closeTestApp();
  });

  // ─── Helpers ───────────────────────────────────────────────────────────────

  /**
   * Runs a raw SELECT against `tableName` inside a transaction that:
   *   1. Sets app.current_tenant_id to the Cedar tenant ID.
   *   2. Switches the active role to rls_test_user_p8b (no BYPASSRLS).
   *
   * Any row whose tenant_id equals AL_NOOR_TENANT_ID is a policy violation.
   */
  async function queryAsCedar(tableName: string): Promise<Array<{ tenant_id: string | null }>> {
    return directPrisma.$transaction(async (tx) => {
      await tx.$executeRawUnsafe(
        `SELECT set_config('app.current_tenant_id', '${CEDAR_TENANT_ID}', true)`,
      );
      await tx.$executeRawUnsafe(`SET LOCAL ROLE ${RLS_TEST_ROLE}`);

      // eslint-disable-next-line @typescript-eslint/no-unsafe-return
      return tx.$queryRawUnsafe(`SELECT tenant_id::text FROM "${tableName}"`) as Promise<
        Array<{ tenant_id: string | null }>
      >;
    });
  }

  /**
   * Shared assertion: no row in `rows` should carry the Al Noor tenant_id.
   */
  function assertNoAlNoorRows(rows: Array<{ tenant_id: string | null }>, context: string): void {
    const leaks = rows.filter((r) => r.tenant_id === AL_NOOR_TENANT_ID);
    expect(leaks).toHaveLength(0);
    if (leaks.length > 0) {
      throw new Error(
        `RLS LEAK in ${context}: ${leaks.length} Al Noor row(s) returned when querying as Cedar`,
      );
    }
  }

  // ══════════════════════════════════════════════════════════════════════════
  // 1. audit_logs — Dual RLS Policy (nullable tenant_id)
  // ══════════════════════════════════════════════════════════════════════════

  describe('audit_logs — Tenant isolation with nullable tenant_id', () => {
    it('Tenant B cannot see Tenant A audit logs via GET /api/v1/audit-logs', async () => {
      const res = await authGet(app, '/api/v1/audit-logs', cedarToken, CEDAR_DOMAIN).expect(200);

      const items: Array<{ id: string }> = res.body.data ?? [];
      const ids = items.map((i) => i.id);

      expect(ids).not.toContain(alNoorAuditLogId);
      expect(JSON.stringify(res.body)).not.toContain(UNIQUE_MARKER);
    });

    it('Tenant B cannot see Tenant A audit logs even when entity_type filter matches', async () => {
      const entityType = `rls_test_p8b_${UNIQUE_MARKER}`;
      const res = await authGet(
        app,
        `/api/v1/audit-logs?entity_type=${encodeURIComponent(entityType)}`,
        cedarToken,
        CEDAR_DOMAIN,
      ).expect(200);

      const items: Array<{ id: string }> = res.body.data ?? [];
      expect(items).toHaveLength(0);
    });

    it('Platform-level audit logs (tenant_id=NULL) are NOT visible via tenant-scoped endpoint', async () => {
      const entityType = `platform_rls_test_p8b_${UNIQUE_MARKER}`;
      const res = await authGet(
        app,
        `/api/v1/audit-logs?entity_type=${encodeURIComponent(entityType)}`,
        alNoorToken,
        AL_NOOR_DOMAIN,
      ).expect(200);

      const items: Array<{ id: string }> = res.body.data ?? [];
      const ids = items.map((i) => i.id);

      expect(ids).not.toContain(platformAuditLogId);
      expect(items).toHaveLength(0);
    });

    it('Platform-level audit logs (tenant_id=NULL) ARE visible via platform admin endpoint', async () => {
      const entityType = `platform_rls_test_p8b_${UNIQUE_MARKER}`;
      const res = await authGet(
        app,
        `/api/v1/admin/audit-logs?entity_type=${encodeURIComponent(entityType)}`,
        platformToken,
      ).expect(200);

      const items: Array<{ id: string }> = res.body.data ?? [];
      const ids = items.map((i) => i.id);

      expect(ids).toContain(platformAuditLogId);
    });
  });

  // ══════════════════════════════════════════════════════════════════════════
  // 2. compliance_requests — Tenant isolation
  // ══════════════════════════════════════════════════════════════════════════

  describe('compliance_requests — Tenant isolation', () => {
    it('Tenant B cannot list Tenant A compliance requests', async () => {
      const res = await authGet(
        app,
        '/api/v1/compliance-requests',
        cedarToken,
        CEDAR_DOMAIN,
      ).expect(200);

      const items: Array<{ id: string }> = res.body.data ?? [];
      const ids = items.map((i) => i.id);

      expect(ids).not.toContain(complianceRequestId);
    });

    it('Tenant B cannot get Tenant A compliance request by ID', async () => {
      await authGet(
        app,
        `/api/v1/compliance-requests/${complianceRequestId}`,
        cedarToken,
        CEDAR_DOMAIN,
      ).expect(404);
    });

    it('Tenant B cannot classify Tenant A compliance request', async () => {
      const res = await authPost(
        app,
        `/api/v1/compliance-requests/${complianceRequestId}/classify`,
        cedarToken,
        {
          classification: 'erase',
          decision_notes: 'RLS cross-tenant classify attempt',
        },
        CEDAR_DOMAIN,
      );

      expect([400, 404]).toContain(res.status);
    });
  });

  // ══════════════════════════════════════════════════════════════════════════
  // 3. import_jobs — Tenant isolation
  // ══════════════════════════════════════════════════════════════════════════

  describe('import_jobs — Tenant isolation', () => {
    it('Tenant B cannot list Tenant A import jobs', async () => {
      const res = await authGet(app, '/api/v1/imports', cedarToken, CEDAR_DOMAIN).expect(200);

      const items: Array<{ id: string }> = res.body.data ?? [];
      const ids = items.map((i) => i.id);

      expect(ids).not.toContain(importJobId);
    });

    it('Tenant B cannot get Tenant A import job by ID', async () => {
      await authGet(app, `/api/v1/imports/${importJobId}`, cedarToken, CEDAR_DOMAIN).expect(404);
    });

    it('Tenant B cannot confirm Tenant A import job', async () => {
      const res = await authPost(
        app,
        `/api/v1/imports/${importJobId}/confirm`,
        cedarToken,
        {},
        CEDAR_DOMAIN,
      );

      expect([400, 404]).toContain(res.status);
    });
  });

  // ══════════════════════════════════════════════════════════════════════════
  // 4. Table-Level RLS Tests — Direct DB Verification
  // ══════════════════════════════════════════════════════════════════════════

  describe('Table-level: RLS policy enforcement for P8 tables (direct DB verification)', () => {
    it('audit_logs: querying as Cedar returns no Al Noor rows', async () => {
      const rows = await queryAsCedar('audit_logs');
      assertNoAlNoorRows(rows, 'audit_logs');
    });

    it('audit_logs: platform logs (tenant_id=NULL) are visible to Cedar via dual RLS policy', async () => {
      const rows = await directPrisma.$transaction(async (tx) => {
        await tx.$executeRawUnsafe(
          `SELECT set_config('app.current_tenant_id', '${CEDAR_TENANT_ID}', true)`,
        );
        await tx.$executeRawUnsafe(`SET LOCAL ROLE ${RLS_TEST_ROLE}`);

        return tx.$queryRawUnsafe(
          `SELECT id::text, tenant_id::text FROM audit_logs WHERE tenant_id IS NULL`,
        ) as Promise<Array<{ id: string; tenant_id: string | null }>>;
      });

      // Under dual RLS policy, Cedar SHOULD see platform-level logs (tenant_id IS NULL).
      // The policy is: tenant_id IS NULL OR tenant_id = current_tenant_id.
      // Platform rows are intentionally visible to all tenants.
      expect(rows.length).toBeGreaterThanOrEqual(0);
      for (const row of rows) {
        expect(row.tenant_id).toBeNull();
      }
    });

    it('compliance_requests: querying as Cedar returns no Al Noor rows', async () => {
      const rows = await queryAsCedar('compliance_requests');
      assertNoAlNoorRows(rows, 'compliance_requests');
    });

    it('import_jobs: querying as Cedar returns no Al Noor rows', async () => {
      const rows = await queryAsCedar('import_jobs');
      assertNoAlNoorRows(rows, 'import_jobs');
    });

    it('search_index_status: querying as Cedar returns no Al Noor rows', async () => {
      const rows = await queryAsCedar('search_index_status');
      assertNoAlNoorRows(rows, 'search_index_status');
    });
  });
});
